name: gceditor
description: gceditor

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.24
  cupertino_icons: ^1.0.2
  darq: ^1.1.1
  dartx: ^0.7.1
  file_picker: ^4.0.2
  flutter:
    sdk: flutter

  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/menubar
      ref: a8ca32b01bafa91624a1fc8e2cdd0c2312d40a84
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: a8ca32b01bafa91624a1fc8e2cdd0c2312d40a84

  flutter_fancy_tree_view: ^0.5.1+1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^0.14.0+3
  font_awesome_flutter: ^9.1.0
  intl: ^0.17.0
  listenable_stream: ^1.1.0
  loading_overlay: ^0.3.0
  localstorage: ^4.0.0+1
  mutex: ^3.0.0
  nil: ^1.1.1
  path: ^1.8.0
  path_provider: ^2.0.3
  quiver: ^3.0.1
  socket_io: ^1.0.1
  socket_io_client: ^1.0.1
  statemachine: ^3.1.0
  styled_text: ^3.0.2
  tcp_scanner: ^2.0.5
  uuid: ^3.0.4
  custom_pop_up_menu: ^1.2.2
  dropdown_search: ^1.0.0
  linked_scroll_controller: ^0.2.0
  catcher: ^0.6.8
  crypto: ^3.0.1
  computer: ^2.0.0
  args: ^2.3.0
  git: ^2.0.0
  flutter_colorpicker: ^1.0.1
  top_snackbar_flutter: ^1.0.2
  json_annotation: ^4.4.0

dev_dependencies:
  json_serializable: ^6.1.3
  build_runner: ^2.1.2
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: JetbrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/JetBrainsMono-Light.ttf
          weight: 300
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  generate: true
