// ignore_for_file: unnecessary_brace_in_string_interps

import 'package:darq/darq.dart';
import 'package:gceditor/model/db/class_field_description_data_info.dart';
import 'package:gceditor/model/db/class_meta_entity.dart';
import 'package:gceditor/model/db/class_meta_entity_enum.dart';
import 'package:gceditor/model/db/class_meta_field_description.dart';
import 'package:gceditor/model/db/db_model.dart';
import 'package:gceditor/model/db/db_model_shared.dart';
import 'package:gceditor/model/db/generator_rust.dart';
import 'package:gceditor/utils/utils.dart';

import 'generators_job.dart';

class GeneratorRustRunner extends BaseGeneratorRunner<GeneratorRust> with OutputFolderSaver, FilesComparer {
  static const _indent = '    ';
  static const _defaultNewLine = '\n';

  static const _paramDate = 'date';
  static const _paramUser = 'user';
  static const _paramPrefix = 'prefix';
  static const _paramPostfix = 'postfix';
  static const _paramEnums = 'enums';
  static const _paramStructs = 'structs';
  static const _paramItemKindEnum = 'itemKindEnum';
  static const _paramTablesStruct = 'tablesStruct';
  static const _paramListsStruct = 'listsStruct';
  static const _paramTableClassMap = 'tableClassMap';
  static const _paramTableParsers = 'tableParsers';
  static const _paramIndexBuilders = 'indexBuilders';
  static const _paramIndexFields = 'indexFields';
  static const _paramModelItemImpls = 'modelItemImpls';
  static const _paramReferenceAccessors = 'referenceAccessors';
  static const _paramGetPathByEnumOverloads = 'getPathByEnumOverloads';
  static const _paramTraits = 'traits';

  @override
  Future<GeneratorResult> execute(String outputFolder, DbModel model, GeneratorRust data, GeneratorAdditionalInformation additionalInfo) async {
    try {
      final result = _rootTemplate.format({
        _paramDate: additionalInfo.date,
        _paramUser: additionalInfo.user,
        _paramPrefix: data.prefix,
        _paramPostfix: data.postfix,
        _paramEnums: _getEnums(model, data),
        _paramStructs: _getStructs(model, data),
        _paramItemKindEnum: _getItemKindEnum(model, data),
        _paramTablesStruct: _getTablesStruct(model, data),
        _paramListsStruct: _getListsStruct(model, data),
        _paramTableClassMap: _getTableClassMap(model, data),
        _paramTableParsers: _getTableParsers(model, data),
        _paramIndexBuilders: _getIndexBuilders(model, data),
        _paramIndexFields: _getIndexFields(model, data),
        _paramModelItemImpls: _getModelItemImpls(model, data),
        _paramReferenceAccessors: _getReferenceAccessors(model, data),
        _paramGetPathByEnumOverloads: _getPathByEnumOverloads(model, data),
        _paramTraits: _getTraits(model, data),
      });

      final previousResult = await readFromFile(
        outputFolder: outputFolder,
        fileName: data.fileName,
        fileExtension: data.fileExtension,
      );

      if (!resultChanged(result, previousResult, '// This file was autogenerated')) {
        return GeneratorResult.success();
      }

      final saveError = await saveToFile(
        outputFolder: outputFolder,
        fileName: data.fileName,
        fileExtension: data.fileExtension,
        data: result,
      );

      if (saveError != null) {
        return GeneratorResult.error(saveError);
      }
    } catch (e) {
      return GeneratorResult.error(e.toString());
    }

    return GeneratorResult.success();
  }

  String _getEnums(DbModel model, GeneratorRust data) {
    final sb = StringBuffer();
    for (final enumEntity in model.cache.allEnums) {
      final typeName = '${data.prefix}${enumEntity.id}${data.postfix}';
      if (enumEntity.description.trim().isNotEmpty) {
        sb.writeln('/// ${enumEntity.description.trim()}');
      }
      sb.writeln('#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, Serialize, Deserialize)]');
      sb.writeln('pub enum $typeName {');
      if (enumEntity.values.isEmpty) {
        sb.writeln('${_indent}#[default]');
        sb.writeln('${_indent}None,');
      } else {
        for (var i = 0; i < enumEntity.values.length; i++) {
          final val = enumEntity.values[i];
          if (i == 0) {
            sb.writeln('${_indent}#[default]');
          }
          sb.writeln('${_indent}${val.id},');
        }
      }
      sb.writeln('}');
      sb.writeln();
      sb.writeln('impl $typeName {');
      sb.writeln('${_indent}pub fn as_str(&self) -> &\'static str {');
      if (enumEntity.values.isEmpty) {
        sb.writeln('${_indent}${_indent}""');
      } else {
        sb.writeln('${_indent}${_indent}match self {');
        for (final val in enumEntity.values) {
          sb.writeln('${_indent}${_indent}${_indent}Self::${val.id} => "${val.id}",');
        }
        sb.writeln('${_indent}${_indent}}');
      }
      sb.writeln('${_indent}}');
      sb.writeln();
      sb.writeln('${_indent}#[allow(clippy::should_implement_trait)]');
      sb.writeln('${_indent}pub fn from_str(s: &str) -> Option<Self> {');
      sb.writeln('${_indent}${_indent}match s {');
      for (final val in enumEntity.values) {
        sb.writeln('${_indent}${_indent}${_indent}"${val.id}" => Some(Self::${val.id}),');
      }
      if (enumEntity.values.isEmpty) {
        sb.writeln('${_indent}${_indent}${_indent}"" | "None" => Some(Self::None),');
      }
      sb.writeln('${_indent}${_indent}${_indent}_ => None,');
      sb.writeln('${_indent}${_indent}}');
      sb.writeln('${_indent}}');
      sb.writeln('}');
      sb.writeln();
      sb.writeln('impl std::str::FromStr for $typeName {');
      sb.writeln('${_indent}type Err = ();');
      sb.writeln('${_indent}fn from_str(s: &str) -> Result<Self, Self::Err> {');
      sb.writeln('${_indent}${_indent}Self::from_str(s).ok_or(())');
      sb.writeln('${_indent}}');
      sb.writeln('}');
      sb.writeln();
    }
    return sb.toString();
  }

  String _getStructs(DbModel model, GeneratorRust data) {
    final items = <String>[];
    for (final classEntity in model.cache.allClasses) {
      if (classEntity.classType == ClassType.undefined || classEntity.classType == ClassType.interface) {
        continue;
      }
      final typeName = '${data.prefix}${classEntity.id}${data.postfix}';
      final isValueType = classEntity.classType == ClassType.valueType;

      final sb = StringBuffer();
      if (classEntity.description.trim().isNotEmpty) {
        sb.writeln('/// ${classEntity.description.trim()}');
      }
      sb.writeln('#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]');
      sb.writeln('pub struct $typeName {');
      if (!isValueType) {
        sb.writeln('${_indent}pub id: String,');
        sb.writeln('${_indent}pub is_global: bool,');
      }
      final allFields = model.cache.getAllFields(classEntity);
      for (final field in allFields) {
        final rustType = _getRustType(model, data, field);
        sb.writeln('${_indent}pub ${field.id}: $rustType,');
      }
      sb.writeln('}');
      sb.writeln();

      items.add(sb.toString());
    }
    return items.join(_defaultNewLine);
  }

  String _getRustType(DbModel model, GeneratorRust data, ClassMetaFieldDescription field) {
    switch (field.typeInfo.type) {
      case ClassFieldType.bool:
        return 'bool';
      case ClassFieldType.int:
        return 'i32';
      case ClassFieldType.long:
      case ClassFieldType.date:
      case ClassFieldType.duration:
        return 'i64';
      case ClassFieldType.float:
        return 'f32';
      case ClassFieldType.double:
        return 'f64';
      case ClassFieldType.string:
      case ClassFieldType.text:
      case ClassFieldType.undefined:
        return 'String';
      case ClassFieldType.color:
        return 'Color';
      case ClassFieldType.vector2:
        return 'Vec2';
      case ClassFieldType.vector2Int:
        return 'IVec2';
      case ClassFieldType.vector3:
        return 'Vec3';
      case ClassFieldType.vector3Int:
        return 'IVec3';
      case ClassFieldType.vector4:
        return 'Vec4';
      case ClassFieldType.vector4Int:
        return 'IVec4';
      case ClassFieldType.rectangle:
        return 'Rect';
      case ClassFieldType.rectangleInt:
        return 'IRect';
      case ClassFieldType.reference:
        final classEntity = model.cache.getEntity(field.typeInfo.classId!);
        if (classEntity is ClassMetaEntityEnum) {
          return '${data.prefix}${classEntity.id}${data.postfix}';
        }
        return 'Option<String>';
      case ClassFieldType.list:
      case ClassFieldType.set:
        final elemType = _getSimpleRustType(model, data, field.valueTypeInfo!);
        return 'Vec<$elemType>';
      case ClassFieldType.listInline:
        final inlineClass = '${data.prefix}${field.valueTypeInfo!.classId!}${data.postfix}';
        return 'Vec<$inlineClass>';
      case ClassFieldType.dictionary:
        final keyType = _getSimpleRustType(model, data, field.keyTypeInfo!);
        final valType = _getSimpleRustType(model, data, field.valueTypeInfo!);
        return 'std::collections::HashMap<$keyType, $valType>';
    }
  }

  String _getSimpleRustType(DbModel model, GeneratorRust data, ClassFieldDescriptionDataInfo type) {
    switch (type.type) {
      case ClassFieldType.bool:
        return 'bool';
      case ClassFieldType.int:
        return 'i32';
      case ClassFieldType.long:
      case ClassFieldType.date:
      case ClassFieldType.duration:
        return 'i64';
      case ClassFieldType.float:
        return 'f32';
      case ClassFieldType.double:
        return 'f64';
      case ClassFieldType.string:
      case ClassFieldType.text:
      case ClassFieldType.undefined:
        return 'String';
      case ClassFieldType.color:
        return 'Color';
      case ClassFieldType.vector2:
        return 'Vec2';
      case ClassFieldType.vector2Int:
        return 'IVec2';
      case ClassFieldType.vector3:
        return 'Vec3';
      case ClassFieldType.vector3Int:
        return 'IVec3';
      case ClassFieldType.vector4:
        return 'Vec4';
      case ClassFieldType.vector4Int:
        return 'IVec4';
      case ClassFieldType.rectangle:
        return 'Rect';
      case ClassFieldType.rectangleInt:
        return 'IRect';
      case ClassFieldType.reference:
        final classEntity = model.cache.getEntity(type.classId!);
        if (classEntity is ClassMetaEntityEnum) {
          return '${data.prefix}${classEntity.id}${data.postfix}';
        }
        return 'String';
      default:
        return 'String';
    }
  }

  List<ClassMetaEntity> _getImplementingTableClasses(DbModel model, ClassMetaEntity entity) {
    final tableClassIds = model.cache.allDataTables.map((t) => t.classId).toSet();
    final implementing = model.cache.getImplementingClasses(entity);
    final allCandidates = [entity, ...implementing];
    final result = <ClassMetaEntity>[];
    final seen = <String>{};
    for (final c in allCandidates) {
      if (c.classType != ClassType.valueType &&
          c.classType != ClassType.undefined &&
          tableClassIds.contains(c.id) &&
          !seen.contains(c.id)) {
        seen.add(c.id);
        result.add(c);
      }
    }
    result.sort((a, b) => a.id.compareTo(b.id));
    return result;
  }

  List<ClassMetaEntity> _getAllTableClasses(DbModel model) {
    final tableClassIds = model.cache.allDataTables.map((t) => t.classId).toSet();
    final result = <ClassMetaEntity>[];
    final seen = <String>{};
    for (final c in model.cache.allClasses) {
      if (c.classType != ClassType.valueType &&
          c.classType != ClassType.undefined &&
          tableClassIds.contains(c.id) &&
          !seen.contains(c.id)) {
        seen.add(c.id);
        result.add(c);
      }
    }
    result.sort((a, b) => a.id.compareTo(b.id));
    return result;
  }

  String _getItemKindEnum(DbModel model, GeneratorRust data) {
    final sb = StringBuffer();
    final generatedRefNames = <String>{};

    for (final classEntity in model.cache.allClasses) {
      if (classEntity.classType == ClassType.undefined || classEntity.classType == ClassType.valueType) {
        continue;
      }
      final implementingTables = _getImplementingTableClasses(model, classEntity);
      if (implementingTables.isEmpty) {
        continue;
      }

      final refName = '${data.prefix}${classEntity.id}Ref';
      generatedRefNames.add(refName);

      sb.writeln('#[derive(Clone, Copy, Debug, PartialEq)]');
      sb.writeln('pub enum $refName<\'a> {');
      for (final tc in implementingTables) {
        final tcTypeName = '${data.prefix}${tc.id}${data.postfix}';
        sb.writeln('${_indent}${tc.id}(&\'a $tcTypeName),');
      }
      sb.writeln('}');
      sb.writeln();

      sb.writeln('impl<\'a> $refName<\'a> {');
      sb.writeln('${_indent}pub fn id(&self) -> &str {');
      sb.writeln('${_indent}${_indent}match self {');
      for (final tc in implementingTables) {
        sb.writeln('${_indent}${_indent}${_indent}Self::${tc.id}(item) => &item.id,');
      }
      sb.writeln('${_indent}${_indent}}');
      sb.writeln('${_indent}}');
      sb.writeln();
      sb.writeln('${_indent}pub fn is_global(&self) -> bool {');
      sb.writeln('${_indent}${_indent}match self {');
      for (final tc in implementingTables) {
        sb.writeln('${_indent}${_indent}${_indent}Self::${tc.id}(item) => item.is_global,');
      }
      sb.writeln('${_indent}${_indent}}');
      sb.writeln('${_indent}}');
      sb.writeln('}');
      sb.writeln();

      // Trait implementations for ref enum
      if (classEntity.classType == ClassType.interface) {
        final ifaces = <ClassMetaEntity>[classEntity, ...model.cache.getParentInterfaces(classEntity)].toSet();
        for (final iface in ifaces) {
          final ifaceTraitName = '${data.prefix}${iface.id}${data.postfix}';
          sb.writeln('impl<\'a> $ifaceTraitName for $refName<\'a> {');
          final validParents = iface.interfaces.whereType<String>().where((i) => i.isNotEmpty).toList();
          final ifaceParentFieldIds = validParents
              .expand((i) => model.cache.getAllFieldsByClassId(i) ?? <ClassMetaFieldDescription>[])
              .map((f) => f.id)
              .toSet();
          for (final field in iface.fields) {
            if (!ifaceParentFieldIds.contains(field.id)) {
              final retType = _getRustGetterReturnType(model, data, field);
              sb.writeln('${_indent}fn ${field.id}(&self) -> $retType {');
              sb.writeln('${_indent}${_indent}match self {');
              for (final tc in implementingTables) {
                sb.writeln('${_indent}${_indent}${_indent}Self::${tc.id}(item) => $ifaceTraitName::${field.id}(*item),');
              }
              sb.writeln('${_indent}${_indent}}');
              sb.writeln('${_indent}}');
            }
          }
          sb.writeln('}');
          sb.writeln();
        }
      } else {
        final classTraits = <ClassMetaEntity>[classEntity, ...model.cache.getParentClasses(classEntity)].toSet();
        for (final c in classTraits) {
          final traitName = '${data.prefix}${c.id}Trait${data.postfix}';
          sb.writeln('impl<\'a> $traitName for $refName<\'a> {');
          final inheritedFieldIds = <String>{};
          if (c.parent != null && c.parent!.isNotEmpty) {
            inheritedFieldIds.addAll(model.cache.getAllFieldsByClassId(c.parent!)?.map((f) => f.id) ?? []);
          }
          for (final iface in c.interfaces.whereType<String>().where((i) => i.isNotEmpty)) {
            inheritedFieldIds.addAll(model.cache.getAllFieldsByClassId(iface)?.map((f) => f.id) ?? []);
          }
          if (c.parent == null || c.parent!.isEmpty) {
            sb.writeln('${_indent}fn id(&self) -> &str {');
            sb.writeln('${_indent}${_indent}match self {');
            for (final tc in implementingTables) {
              sb.writeln('${_indent}${_indent}${_indent}Self::${tc.id}(item) => $traitName::id(*item),');
            }
            sb.writeln('${_indent}${_indent}}');
            sb.writeln('${_indent}}');
            sb.writeln('${_indent}fn is_global(&self) -> bool {');
            sb.writeln('${_indent}${_indent}match self {');
            for (final tc in implementingTables) {
              sb.writeln('${_indent}${_indent}${_indent}Self::${tc.id}(item) => $traitName::is_global(*item),');
            }
            sb.writeln('${_indent}${_indent}}');
            sb.writeln('${_indent}}');
          }
          for (final field in c.fields) {
            if (!inheritedFieldIds.contains(field.id)) {
              final retType = _getRustGetterReturnType(model, data, field);
              sb.writeln('${_indent}fn ${field.id}(&self) -> $retType {');
              sb.writeln('${_indent}${_indent}match self {');
              for (final tc in implementingTables) {
                sb.writeln('${_indent}${_indent}${_indent}Self::${tc.id}(item) => $traitName::${field.id}(*item),');
              }
              sb.writeln('${_indent}${_indent}}');
              sb.writeln('${_indent}}');
            }
          }
          sb.writeln('}');
          sb.writeln();
        }

        final allInterfaces = _getAllInterfaces(model, classEntity);
        for (final iface in allInterfaces) {
          final ifaceTraitName = '${data.prefix}${iface.id}${data.postfix}';
          sb.writeln('impl<\'a> $ifaceTraitName for $refName<\'a> {');
          final ifaceValidParents = iface.interfaces.whereType<String>().where((i) => i.isNotEmpty).toList();
          final ifaceParentFieldIds = ifaceValidParents
              .expand((i) => model.cache.getAllFieldsByClassId(i) ?? <ClassMetaFieldDescription>[])
              .map((f) => f.id)
              .toSet();
          for (final field in iface.fields) {
            if (!ifaceParentFieldIds.contains(field.id)) {
              final retType = _getRustGetterReturnType(model, data, field);
              sb.writeln('${_indent}fn ${field.id}(&self) -> $retType {');
              sb.writeln('${_indent}${_indent}match self {');
              for (final tc in implementingTables) {
                sb.writeln('${_indent}${_indent}${_indent}Self::${tc.id}(item) => $ifaceTraitName::${field.id}(*item),');
              }
              sb.writeln('${_indent}${_indent}}');
              sb.writeln('${_indent}}');
            }
          }
          sb.writeln('}');
          sb.writeln();
        }
      }

      // ModelCollection & ModelItemLookup
      sb.writeln('impl<\'a> ${data.prefix}Collection<\'a> for $refName<\'a> {');
      sb.writeln('${_indent}type Output = Vec<Self>;');
      sb.writeln('${_indent}fn get_all_from_root(root: &\'a ${data.prefix}Root${data.postfix}) -> Self::Output {');
      sb.writeln('${_indent}${_indent}let mut result = Vec::new();');
      for (final tc in implementingTables) {
        final tables = model.cache.allDataTables.where((t) => t.classId == tc.id);
        for (final t in tables) {
          sb.writeln('${_indent}${_indent}for item in &root.tables.${t.id} {');
          sb.writeln('${_indent}${_indent}${_indent}result.push(Self::${tc.id}(item));');
          sb.writeln('${_indent}${_indent}}');
        }
      }
      sb.writeln('${_indent}${_indent}result');
      sb.writeln('${_indent}}');
      sb.writeln('}');
      sb.writeln();

      sb.writeln('impl<\'a> ${data.prefix}ItemLookup<\'a> for $refName<\'a> {');
      sb.writeln('${_indent}type Output = Self;');
      sb.writeln('${_indent}fn get_from_root(root: &\'a ${data.prefix}Root${data.postfix}, id: &str) -> Option<Self::Output> {');
      for (final tc in implementingTables) {
        final tables = model.cache.allDataTables.where((t) => t.classId == tc.id);
        final lowerName = tc.id.toLowerCase();
        for (final t in tables) {
          sb.writeln('${_indent}${_indent}if let Some(&idx) = root.${lowerName}_by_id.get(id) {');
          sb.writeln('${_indent}${_indent}${_indent}return Some(Self::${tc.id}(&root.tables.${t.id}[idx]));');
          sb.writeln('${_indent}${_indent}}');
        }
      }
      sb.writeln('${_indent}${_indent}None');
      sb.writeln('${_indent}}');
      sb.writeln('}');
      sb.writeln();
    }

    final rootItemRefName = '${data.prefix}ItemRef';
    if (!generatedRefNames.contains(rootItemRefName)) {
      final allTableClasses = _getAllTableClasses(model);
      if (allTableClasses.isNotEmpty) {
        sb.writeln('#[derive(Clone, Copy, Debug, PartialEq)]');
        sb.writeln('pub enum $rootItemRefName<\'a> {');
        for (final tc in allTableClasses) {
          final tcTypeName = '${data.prefix}${tc.id}${data.postfix}';
          sb.writeln('${_indent}${tc.id}(&\'a $tcTypeName),');
        }
        sb.writeln('}');
        sb.writeln();

        sb.writeln('impl<\'a> $rootItemRefName<\'a> {');
        sb.writeln('${_indent}pub fn id(&self) -> &str {');
        sb.writeln('${_indent}${_indent}match self {');
        for (final tc in allTableClasses) {
          sb.writeln('${_indent}${_indent}${_indent}Self::${tc.id}(item) => &item.id,');
        }
        sb.writeln('${_indent}${_indent}}');
        sb.writeln('${_indent}}');
        sb.writeln();
        sb.writeln('${_indent}pub fn is_global(&self) -> bool {');
        sb.writeln('${_indent}${_indent}match self {');
        for (final tc in allTableClasses) {
          sb.writeln('${_indent}${_indent}${_indent}Self::${tc.id}(item) => item.is_global,');
        }
        sb.writeln('${_indent}${_indent}}');
        sb.writeln('${_indent}}');
        sb.writeln('}');
        sb.writeln();

        sb.writeln('impl<\'a> ${data.prefix}Collection<\'a> for $rootItemRefName<\'a> {');
        sb.writeln('${_indent}type Output = Vec<Self>;');
        sb.writeln('${_indent}fn get_all_from_root(root: &\'a ${data.prefix}Root${data.postfix}) -> Self::Output {');
        sb.writeln('${_indent}${_indent}let mut result = Vec::new();');
        for (final tc in allTableClasses) {
          final tables = model.cache.allDataTables.where((t) => t.classId == tc.id);
          for (final t in tables) {
            sb.writeln('${_indent}${_indent}for item in &root.tables.${t.id} {');
            sb.writeln('${_indent}${_indent}${_indent}result.push(Self::${tc.id}(item));');
            sb.writeln('${_indent}${_indent}}');
          }
        }
        sb.writeln('${_indent}${_indent}result');
        sb.writeln('${_indent}}');
        sb.writeln('}');
        sb.writeln();

        sb.writeln('impl<\'a> ${data.prefix}ItemLookup<\'a> for $rootItemRefName<\'a> {');
        sb.writeln('${_indent}type Output = Self;');
        sb.writeln('${_indent}fn get_from_root(root: &\'a ${data.prefix}Root${data.postfix}, id: &str) -> Option<Self::Output> {');
        for (final tc in allTableClasses) {
          final tables = model.cache.allDataTables.where((t) => t.classId == tc.id);
          final lowerName = tc.id.toLowerCase();
          for (final t in tables) {
            sb.writeln('${_indent}${_indent}if let Some(&idx) = root.${lowerName}_by_id.get(id) {');
            sb.writeln('${_indent}${_indent}${_indent}return Some(Self::${tc.id}(&root.tables.${t.id}[idx]));');
            sb.writeln('${_indent}${_indent}}');
          }
        }
        sb.writeln('${_indent}${_indent}None');
        sb.writeln('${_indent}}');
        sb.writeln('}');
        sb.writeln();
      }
    }

    return sb.toString();
  }

  String _getTablesStruct(DbModel model, GeneratorRust data) {
    final sb = StringBuffer();
    sb.writeln('#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]');
    sb.writeln('pub struct TablesList {');
    for (final table in model.cache.allDataTables) {
      final className = '${data.prefix}${table.classId}${data.postfix}';
      sb.writeln('${_indent}pub ${table.id}: Vec<$className>,');
    }
    sb.writeln('}');
    return sb.toString();
  }

  String _getListsStruct(DbModel model, GeneratorRust data) {
    final sb = StringBuffer();
    sb.writeln('#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]');
    sb.writeln('pub struct ItemsLists {');
    for (final classEntity in model.cache.allClasses) {
      if (classEntity.exportList != true) continue;
      final thisAndParentClasses = model.cache.getImplementingClasses(classEntity).concat([classEntity]).map((e) => e.id).toSet();
      final allItems = model.cache.allDataTables
          .where((element) => thisAndParentClasses.contains(element.classId))
          .toMap((e) => MapEntry(e.classId, e.rows));
      for (final kvp in allItems.entries) {
        for (final row in kvp.value) {
          if (row.id.isNotEmpty) {
            sb.writeln('${_indent}pub ${row.id.toLowerCase()}: Option<String>,');
          }
        }
      }
    }
    sb.writeln('}');
    return sb.toString();
  }

  String _getTableClassMap(DbModel model, GeneratorRust data) {
    final sb = StringBuffer();
    for (final table in model.cache.allDataTables) {
      sb.writeln('${_indent}${_indent}"${table.id}" => "${table.classId}",');
    }
    return sb.toString();
  }

  String _getTableParsers(DbModel model, GeneratorRust data) {
    final sb = StringBuffer();
    for (final table in model.cache.allDataTables) {
      final className = '${data.prefix}${table.classId}${data.postfix}';
      final classEntity = model.cache.getEntity(table.classId) as ClassMetaEntity?;
      if (classEntity == null) continue;

      sb.writeln('${_indent}${_indent}if let Some(list) = tables_val.get("${table.id}").and_then(|v| v.as_array()) {');
      sb.writeln('${_indent}${_indent}${_indent}for (row_idx, row_val) in list.iter().enumerate() {');
      sb.writeln('${_indent}${_indent}${_indent}${_indent}if let Some(row_map) = row_val.as_object() {');
      sb.writeln('${_indent}${_indent}${_indent}${_indent}${_indent}let id = row_map.get("id").and_then(|v| v.as_str()).map(|s| s.to_string()).unwrap_or_else(|| format!("${table.id}_{row_idx}"));');
      sb.writeln('${_indent}${_indent}${_indent}${_indent}${_indent}let is_global = row_map.contains_key("id");');
      sb.writeln('${_indent}${_indent}${_indent}${_indent}${_indent}let item = $className {');
      sb.writeln('${_indent}${_indent}${_indent}${_indent}${_indent}${_indent}id: id.clone(),');
      sb.writeln('${_indent}${_indent}${_indent}${_indent}${_indent}${_indent}is_global,');

      final allFields = model.cache.getAllFields(classEntity);
      for (final field in allFields) {
        final parseExpr = _getFieldParseExpr(model, data, field);
        sb.writeln('${_indent}${_indent}${_indent}${_indent}${_indent}${_indent}${field.id}: $parseExpr,');
      }

      sb.writeln('${_indent}${_indent}${_indent}${_indent}${_indent}};');
      sb.writeln('${_indent}${_indent}${_indent}${_indent}${_indent}tables.${table.id}.push(item);');
      sb.writeln('${_indent}${_indent}${_indent}${_indent}}');
      sb.writeln('${_indent}${_indent}${_indent}}');
      sb.writeln('${_indent}${_indent}}');
    }
    return sb.toString();
  }

  String _getFieldParseExpr(DbModel model, GeneratorRust data, ClassMetaFieldDescription field) {
    final rawVal = 'row_map.get("${field.id}")';
    switch (field.typeInfo.type) {
      case ClassFieldType.bool:
        return 'parse_bool($rawVal)';
      case ClassFieldType.int:
        return 'parse_i32($rawVal)';
      case ClassFieldType.long:
      case ClassFieldType.date:
      case ClassFieldType.duration:
        return 'parse_i64($rawVal)';
      case ClassFieldType.float:
        return 'parse_f32($rawVal)';
      case ClassFieldType.double:
        return 'parse_f64($rawVal)';
      case ClassFieldType.string:
      case ClassFieldType.text:
      case ClassFieldType.undefined:
        return 'parse_string($rawVal)';
      case ClassFieldType.color:
        return 'parse_color($rawVal)';
      case ClassFieldType.vector2:
        return 'parse_vec2($rawVal)';
      case ClassFieldType.vector2Int:
        return 'parse_ivec2($rawVal)';
      case ClassFieldType.vector3:
        return 'parse_vec3($rawVal)';
      case ClassFieldType.vector3Int:
        return 'parse_ivec3($rawVal)';
      case ClassFieldType.vector4:
        return 'parse_vec4($rawVal)';
      case ClassFieldType.vector4Int:
        return 'parse_ivec4($rawVal)';
      case ClassFieldType.rectangle:
        return 'parse_rect($rawVal)';
      case ClassFieldType.rectangleInt:
        return 'parse_irect($rawVal)';
      case ClassFieldType.reference:
        final classEntity = model.cache.getEntity(field.typeInfo.classId!);
        if (classEntity is ClassMetaEntityEnum) {
          final enumType = '${data.prefix}${classEntity.id}${data.postfix}';
          return 'parse_string($rawVal).as_str().pipe($enumType::from_str).unwrap_or_default()';
        }
        return '$rawVal.and_then(|v| v.as_str()).map(|s| s.to_string())';
      case ClassFieldType.list:
      case ClassFieldType.set:
        final elemParser = _getSimpleElementParser(model, data, field.valueTypeInfo!);
        return 'parse_vec($rawVal, $elemParser)';
      case ClassFieldType.listInline:
        final inlineClassId = field.valueTypeInfo!.classId!;
        final inlineClassName = '${data.prefix}$inlineClassId${data.postfix}';
        final inlineEntity = model.cache.getEntity(inlineClassId) as ClassMetaEntity?;
        final inlineFields = inlineEntity != null ? model.cache.getAllFields(inlineEntity) : <ClassMetaFieldDescription>[];
        final fieldInitsList = <String>[];
        if (inlineEntity != null && inlineEntity.classType != ClassType.valueType) {
          fieldInitsList.add('id: sub_map.get("id").and_then(|v| v.as_str()).unwrap_or("").to_string()');
          fieldInitsList.add('is_global: sub_map.contains_key("id")');
        }
        for (final f in inlineFields) {
          fieldInitsList.add('${f.id}: ${_getFieldParseExpr(model, data, f).replaceAll('row_map', 'sub_map')}');
        }
        final fieldInits = fieldInitsList.join(', ');
        return 'parse_vec($rawVal, |v| v.as_object().map(|sub_map| $inlineClassName { $fieldInits }).unwrap_or_default())';
      case ClassFieldType.dictionary:
        final valParser = _getSimpleElementParser(model, data, field.valueTypeInfo!);
        return 'parse_hash_map($rawVal, $valParser)';
    }
  }

  String _getSimpleElementParser(DbModel model, GeneratorRust data, ClassFieldDescriptionDataInfo type) {
    switch (type.type) {
      case ClassFieldType.bool:
        return '|v| parse_bool(Some(v))';
      case ClassFieldType.int:
        return '|v| parse_i32(Some(v))';
      case ClassFieldType.long:
      case ClassFieldType.date:
      case ClassFieldType.duration:
        return '|v| parse_i64(Some(v))';
      case ClassFieldType.float:
        return '|v| parse_f32(Some(v))';
      case ClassFieldType.double:
        return '|v| parse_f64(Some(v))';
      case ClassFieldType.string:
      case ClassFieldType.text:
      case ClassFieldType.undefined:
        return '|v| parse_string(Some(v))';
      case ClassFieldType.color:
        return '|v| parse_color(Some(v))';
      case ClassFieldType.vector2:
        return '|v| parse_vec2(Some(v))';
      case ClassFieldType.vector2Int:
        return '|v| parse_ivec2(Some(v))';
      case ClassFieldType.vector3:
        return '|v| parse_vec3(Some(v))';
      case ClassFieldType.vector3Int:
        return '|v| parse_ivec3(Some(v))';
      case ClassFieldType.vector4:
        return '|v| parse_vec4(Some(v))';
      case ClassFieldType.vector4Int:
        return '|v| parse_ivec4(Some(v))';
      case ClassFieldType.rectangle:
        return '|v| parse_rect(Some(v))';
      case ClassFieldType.rectangleInt:
        return '|v| parse_irect(Some(v))';
      case ClassFieldType.reference:
        final classEntity = model.cache.getEntity(type.classId!);
        if (classEntity is ClassMetaEntityEnum) {
          final enumType = '${data.prefix}${classEntity.id}${data.postfix}';
          return '|v| parse_string(Some(v)).as_str().pipe($enumType::from_str).unwrap_or_default()';
        }
        return '|v| parse_string(Some(v))';
      default:
        return '|v| parse_string(Some(v))';
    }
  }

  String _getIndexFields(DbModel model, GeneratorRust data) {
    final sb = StringBuffer();
    for (final classEntity in model.cache.allClasses) {
      if (classEntity.classType != ClassType.referenceType) continue;
      sb.writeln('${_indent}${classEntity.id.toLowerCase()}_by_id: std::collections::HashMap<String, usize>,');
    }
    return sb.toString();
  }

  String _getIndexBuilders(DbModel model, GeneratorRust data) {
    final sb = StringBuffer();
    for (final table in model.cache.allDataTables) {
      final classEntity = model.cache.getEntity(table.classId) as ClassMetaEntity?;
      if (classEntity == null || classEntity.classType != ClassType.referenceType) continue;
      final lowerName = classEntity.id.toLowerCase();
      sb.writeln('${_indent}${_indent}for (idx, item) in root.tables.${table.id}.iter().enumerate() {');
      sb.writeln('${_indent}${_indent}${_indent}root.${lowerName}_by_id.insert(item.id.clone(), idx);');
      sb.writeln('${_indent}${_indent}}');
    }
    return sb.toString();
  }

  String _getModelItemImpls(DbModel model, GeneratorRust data) {
    final sb = StringBuffer();
    final seenClassIds = <String>{};
    for (final table in model.cache.allDataTables) {
      if (seenClassIds.contains(table.classId)) continue;
      seenClassIds.add(table.classId);

      final classEntity = model.cache.getEntity(table.classId) as ClassMetaEntity?;
      if (classEntity == null || classEntity.classType != ClassType.referenceType) continue;
      final className = '${data.prefix}${classEntity.id}${data.postfix}';
      final lowerName = classEntity.id.toLowerCase();

      sb.writeln('impl ${data.prefix}ModelItem for $className {');
      sb.writeln('${_indent}fn get_from_root<\'a>(root: &\'a ${data.prefix}Root${data.postfix}, id: &str) -> Option<&\'a Self> {');
      sb.writeln('${_indent}${_indent}root.${lowerName}_by_id.get(id).map(|&idx| &root.tables.${table.id}[idx])');
      sb.writeln('${_indent}}');
      sb.writeln('${_indent}fn get_all_from_root(root: &${data.prefix}Root${data.postfix}) -> &[Self] {');
      sb.writeln('${_indent}${_indent}&root.tables.${table.id}');
      sb.writeln('${_indent}}');
      sb.writeln('}');
      sb.writeln();

      sb.writeln('impl<\'a> ${data.prefix}Collection<\'a> for $className {');
      sb.writeln('${_indent}type Output = &\'a [Self];');
      sb.writeln('${_indent}fn get_all_from_root(root: &\'a ${data.prefix}Root${data.postfix}) -> Self::Output {');
      sb.writeln('${_indent}${_indent}&root.tables.${table.id}');
      sb.writeln('${_indent}}');
      sb.writeln('}');
      sb.writeln();

      sb.writeln('impl<\'a> ${data.prefix}ItemLookup<\'a> for $className {');
      sb.writeln('${_indent}type Output = &\'a Self;');
      sb.writeln('${_indent}fn get_from_root(root: &\'a ${data.prefix}Root${data.postfix}, id: &str) -> Option<Self::Output> {');
      sb.writeln('${_indent}${_indent}root.${lowerName}_by_id.get(id).map(|&idx| &root.tables.${table.id}[idx])');
      sb.writeln('${_indent}}');
      sb.writeln('}');
      sb.writeln();
    }
    return sb.toString();
  }

  String _getReferenceAccessors(DbModel model, GeneratorRust data) {
    final sb = StringBuffer();
    for (final classEntity in model.cache.allClasses) {
      if (classEntity.classType == ClassType.undefined || classEntity.classType == ClassType.interface) continue;
      final className = '${data.prefix}${classEntity.id}${data.postfix}';
      final accessors = <String>[];

      for (final field in model.cache.getAllFields(classEntity)) {
        if (field.typeInfo.type == ClassFieldType.reference) {
          final targetClass = model.cache.getEntity(field.typeInfo.classId!);
          if (targetClass is ClassMetaEntity) {
            final targetHasTable = model.cache.allDataTables.any((t) => t.classId == targetClass.id);
            if (targetHasTable) {
              final targetTypeName = '${data.prefix}${targetClass.id}${data.postfix}';
              accessors.add('''${_indent}pub fn ${field.id}<\'a>(&self, root: &\'a ${data.prefix}Root${data.postfix}) -> Option<&\'a $targetTypeName> {
${_indent}${_indent}self.${field.id}.as_deref().and_then(|id| root.get::<$targetTypeName>(id))
${_indent}}''');
            } else {
              final implementingTables = _getImplementingTableClasses(model, targetClass);
              if (implementingTables.isNotEmpty) {
                final targetRefName = '${data.prefix}${targetClass.id}Ref';
                accessors.add('''${_indent}pub fn ${field.id}<\'a>(&self, root: &\'a ${data.prefix}Root${data.postfix}) -> Option<$targetRefName<\'a>> {
${_indent}${_indent}self.${field.id}.as_deref().and_then(|id| root.get::<$targetRefName<\'a>>(id))
${_indent}}''');
              }
            }
          }
        }
      }

      if (accessors.isNotEmpty) {
        sb.writeln('impl $className {');
        for (final acc in accessors) {
          sb.writeln(acc);
        }
        sb.writeln('}');
        sb.writeln();
      }
    }
    return sb.toString();
  }

  String _getPathByEnumOverloads(DbModel model, GeneratorRust data) {
    final sb = StringBuffer();
    for (final enumEntity in model.cache.allEnums) {
      if (enumEntity.autoByFile) {
        final typeName = '${data.prefix}${enumEntity.id}${data.postfix}';
        sb.writeln('${_indent}pub fn get_path_by_${enumEntity.id.toLowerCase()}(&self, value: $typeName) -> Option<&str> {');
        sb.writeln('${_indent}${_indent}self.path_by_enum.get("${enumEntity.id}").and_then(|m| m.get(value.as_str())).map(|s| s.as_str())');
        sb.writeln('${_indent}}');
      }
    }
    return sb.toString();
  }

  Set<ClassMetaEntity> _getAllInterfaces(DbModel model, ClassMetaEntity classEntity) {
    final result = <ClassMetaEntity>{};

    void collectFrom(ClassMetaEntity entity) {
      final ifaces = model.cache.getParentInterfaces(entity);
      for (final iface in ifaces) {
        result.add(iface);
      }
    }

    collectFrom(classEntity);

    final parentClasses = model.cache.getParentClasses(classEntity);
    for (final parent in parentClasses) {
      collectFrom(parent);
    }

    return result;
  }

  String _getRustGetterReturnType(DbModel model, GeneratorRust data, ClassMetaFieldDescription field) {
    switch (field.typeInfo.type) {
      case ClassFieldType.bool:
        return 'bool';
      case ClassFieldType.int:
        return 'i32';
      case ClassFieldType.long:
      case ClassFieldType.date:
      case ClassFieldType.duration:
        return 'i64';
      case ClassFieldType.float:
        return 'f32';
      case ClassFieldType.double:
        return 'f64';
      case ClassFieldType.string:
      case ClassFieldType.text:
      case ClassFieldType.undefined:
        return '&str';
      case ClassFieldType.color:
        return 'Color';
      case ClassFieldType.vector2:
        return 'Vec2';
      case ClassFieldType.vector2Int:
        return 'IVec2';
      case ClassFieldType.vector3:
        return 'Vec3';
      case ClassFieldType.vector3Int:
        return 'IVec3';
      case ClassFieldType.vector4:
        return 'Vec4';
      case ClassFieldType.vector4Int:
        return 'IVec4';
      case ClassFieldType.rectangle:
        return 'Rect';
      case ClassFieldType.rectangleInt:
        return 'IRect';
      case ClassFieldType.reference:
        final classEntity = model.cache.getEntity(field.typeInfo.classId!);
        if (classEntity is ClassMetaEntityEnum) {
          return '${data.prefix}${classEntity.id}${data.postfix}';
        }
        return 'Option<&str>';
      case ClassFieldType.list:
      case ClassFieldType.set:
        final elemType = _getSimpleRustType(model, data, field.valueTypeInfo!);
        return '&[$elemType]';
      case ClassFieldType.listInline:
        final inlineClass = '${data.prefix}${field.valueTypeInfo!.classId!}${data.postfix}';
        return '&[$inlineClass]';
      case ClassFieldType.dictionary:
        final keyType = _getSimpleRustType(model, data, field.keyTypeInfo!);
        final valType = _getSimpleRustType(model, data, field.valueTypeInfo!);
        return '&std::collections::HashMap<$keyType, $valType>';
    }
  }

  String _getRustGetterReturnValue(DbModel model, GeneratorRust data, ClassMetaFieldDescription field) {
    switch (field.typeInfo.type) {
      case ClassFieldType.bool:
      case ClassFieldType.int:
      case ClassFieldType.long:
      case ClassFieldType.date:
      case ClassFieldType.duration:
      case ClassFieldType.float:
      case ClassFieldType.double:
      case ClassFieldType.color:
      case ClassFieldType.vector2:
      case ClassFieldType.vector2Int:
      case ClassFieldType.vector3:
      case ClassFieldType.vector3Int:
      case ClassFieldType.vector4:
      case ClassFieldType.vector4Int:
      case ClassFieldType.rectangle:
      case ClassFieldType.rectangleInt:
        return 'self.${field.id}';
      case ClassFieldType.string:
      case ClassFieldType.text:
      case ClassFieldType.undefined:
        return '&self.${field.id}';
      case ClassFieldType.reference:
        final classEntity = model.cache.getEntity(field.typeInfo.classId!);
        if (classEntity is ClassMetaEntityEnum) {
          return 'self.${field.id}';
        }
        return 'self.${field.id}.as_deref()';
      case ClassFieldType.list:
      case ClassFieldType.set:
      case ClassFieldType.listInline:
      case ClassFieldType.dictionary:
        return '&self.${field.id}';
    }
  }

  String _getTraits(DbModel model, GeneratorRust data) {
    final sb = StringBuffer();

    // 1. Interface traits
    final interfaceEntities = model.cache.allClasses
        .where((c) => c.classType == ClassType.interface)
        .orderBy((c) => model.cache.getParentInterfaces(c).length)
        .toList();

    for (final iface in interfaceEntities) {
      final traitName = '${data.prefix}${iface.id}${data.postfix}';
      final validParents = iface.interfaces.whereType<String>().where((i) => i.isNotEmpty).toList();
      final superTraitsStr = validParents.isNotEmpty
          ? ': ${validParents.map((i) => '${data.prefix}$i${data.postfix}').join(' + ')}'
          : '';

      if (iface.description.trim().isNotEmpty) {
        sb.writeln('/// ${iface.description.trim()}');
      }
      sb.writeln('pub trait $traitName$superTraitsStr {');

      final parentFieldIds = validParents
          .expand((i) => model.cache.getAllFieldsByClassId(i) ?? <ClassMetaFieldDescription>[])
          .map((f) => f.id)
          .toSet();

      for (final field in iface.fields) {
        if (!parentFieldIds.contains(field.id)) {
          final retType = _getRustGetterReturnType(model, data, field);
          sb.writeln('${_indent}fn ${field.id}(&self) -> $retType;');
        }
      }
      sb.writeln('}');
      sb.writeln();
    }

    // 2. Class inheritance traits
    final classEntities = model.cache.allClasses
        .where((c) => c.classType != ClassType.interface && c.classType != ClassType.undefined)
        .orderBy((c) => model.cache.getParentClasses(c).length)
        .toList();

    for (final classEntity in classEntities) {
      final traitName = '${data.prefix}${classEntity.id}Trait${data.postfix}';
      final superTraits = <String>[];
      if (classEntity.parent != null && classEntity.parent!.isNotEmpty) {
        superTraits.add('${data.prefix}${classEntity.parent}${data.postfix}Trait');
      }
      for (final iface in classEntity.interfaces.whereType<String>().where((i) => i.isNotEmpty)) {
        superTraits.add('${data.prefix}$iface${data.postfix}');
      }
      final superTraitsStr = superTraits.isNotEmpty ? ': ${superTraits.join(' + ')}' : '';

      if (classEntity.description.trim().isNotEmpty) {
        sb.writeln('/// ${classEntity.description.trim()}');
      }
      sb.writeln('pub trait $traitName$superTraitsStr {');

      final inheritedFieldIds = <String>{};
      if (classEntity.parent != null && classEntity.parent!.isNotEmpty) {
        inheritedFieldIds.addAll(model.cache.getAllFieldsByClassId(classEntity.parent!)?.map((f) => f.id) ?? []);
      }
      for (final iface in classEntity.interfaces.whereType<String>().where((i) => i.isNotEmpty)) {
        inheritedFieldIds.addAll(model.cache.getAllFieldsByClassId(iface)?.map((f) => f.id) ?? []);
      }

      if (classEntity.classType == ClassType.referenceType && (classEntity.parent == null || classEntity.parent!.isEmpty)) {
        sb.writeln('${_indent}fn id(&self) -> &str;');
        sb.writeln('${_indent}fn is_global(&self) -> bool;');
      }

      for (final field in classEntity.fields) {
        if (!inheritedFieldIds.contains(field.id)) {
          final retType = _getRustGetterReturnType(model, data, field);
          sb.writeln('${_indent}fn ${field.id}(&self) -> $retType;');
        }
      }
      sb.writeln('}');
      sb.writeln();
    }

    // 3. Trait implementations on structs
    for (final classEntity in classEntities) {
      final structName = '${data.prefix}${classEntity.id}${data.postfix}';

      // 3a. Implement own trait
      final ownTraitName = '${data.prefix}${classEntity.id}Trait${data.postfix}';
      sb.writeln('impl $ownTraitName for $structName {');

      final ownInheritedFieldIds = <String>{};
      if (classEntity.parent != null && classEntity.parent!.isNotEmpty) {
        ownInheritedFieldIds.addAll(model.cache.getAllFieldsByClassId(classEntity.parent!)?.map((f) => f.id) ?? []);
      }
      for (final iface in classEntity.interfaces.whereType<String>().where((i) => i.isNotEmpty)) {
        ownInheritedFieldIds.addAll(model.cache.getAllFieldsByClassId(iface)?.map((f) => f.id) ?? []);
      }

      if (classEntity.classType == ClassType.referenceType && (classEntity.parent == null || classEntity.parent!.isEmpty)) {
        sb.writeln('${_indent}fn id(&self) -> &str { &self.id }');
        sb.writeln('${_indent}fn is_global(&self) -> bool { self.is_global }');
      }

      for (final field in classEntity.fields) {
        if (!ownInheritedFieldIds.contains(field.id)) {
          final retType = _getRustGetterReturnType(model, data, field);
          final retVal = _getRustGetterReturnValue(model, data, field);
          sb.writeln('${_indent}fn ${field.id}(&self) -> $retType { $retVal }');
        }
      }
      sb.writeln('}');
      sb.writeln();

      // 3b. Implement all ancestor class traits
      final parentClasses = model.cache.getParentClasses(classEntity);
      for (final parent in parentClasses) {
        final parentTraitName = '${data.prefix}${parent.id}Trait${data.postfix}';
        sb.writeln('impl $parentTraitName for $structName {');

        final parentInheritedFieldIds = <String>{};
        if (parent.parent != null && parent.parent!.isNotEmpty) {
          parentInheritedFieldIds.addAll(model.cache.getAllFieldsByClassId(parent.parent!)?.map((f) => f.id) ?? []);
        }
        for (final iface in parent.interfaces.whereType<String>().where((i) => i.isNotEmpty)) {
          parentInheritedFieldIds.addAll(model.cache.getAllFieldsByClassId(iface)?.map((f) => f.id) ?? []);
        }

        if (parent.classType == ClassType.referenceType && (parent.parent == null || parent.parent!.isEmpty)) {
          sb.writeln('${_indent}fn id(&self) -> &str { &self.id }');
          sb.writeln('${_indent}fn is_global(&self) -> bool { self.is_global }');
        }

        for (final field in parent.fields) {
          if (!parentInheritedFieldIds.contains(field.id)) {
            final retType = _getRustGetterReturnType(model, data, field);
            final retVal = _getRustGetterReturnValue(model, data, field);
            sb.writeln('${_indent}fn ${field.id}(&self) -> $retType { $retVal }');
          }
        }
        sb.writeln('}');
        sb.writeln();
      }

      // 3c. Implement all interfaces (direct and inherited)
      final allInterfaces = _getAllInterfaces(model, classEntity).toList()
        ..sort((a, b) => model.cache.getParentInterfaces(a).length.compareTo(model.cache.getParentInterfaces(b).length));

      for (final iface in allInterfaces) {
        final ifaceTraitName = '${data.prefix}${iface.id}${data.postfix}';
        sb.writeln('impl $ifaceTraitName for $structName {');

        final ifaceValidParents = iface.interfaces.whereType<String>().where((i) => i.isNotEmpty).toList();
        final ifaceParentFieldIds = ifaceValidParents
            .expand((i) => model.cache.getAllFieldsByClassId(i) ?? <ClassMetaFieldDescription>[])
            .map((f) => f.id)
            .toSet();

        for (final field in iface.fields) {
          if (!ifaceParentFieldIds.contains(field.id)) {
            final retType = _getRustGetterReturnType(model, data, field);
            final retVal = _getRustGetterReturnValue(model, data, field);
            sb.writeln('${_indent}fn ${field.id}(&self) -> $retType { $retVal }');
          }
        }
        sb.writeln('}');
        sb.writeln();
      }
    }

    return sb.toString();
  }

  final String _rootTemplate = '''// This file was autogenerated via gceditor https://github.com/kennelken/gceditor_fl
// {${_paramDate}}
// by {${_paramUser}}
//
// Dependencies required in Cargo.toml:
// serde = { version = "1.0", features = ["derive"] }
// serde_json = "1.0"
// bevy_math = "0.14"

#![allow(unused_imports, dead_code, unused_variables, non_snake_case, clippy::all)]

use bevy_math::{IVec2, IVec3, IVec4, IRect, Rect, Vec2, Vec3, Vec4};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

// #region Color and Geometry Helpers
#[derive(Clone, Copy, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Color {
    pub r: f32,
    pub g: f32,
    pub b: f32,
    pub a: f32,
}

impl Color {
    pub fn from_argb(argb: i64) -> Self {
        Self {
            a: ((argb >> 24) & 0xFF) as f32 / 255.0,
            r: ((argb >> 16) & 0xFF) as f32 / 255.0,
            g: ((argb >> 8) & 0xFF) as f32 / 255.0,
            b: (argb & 0xFF) as f32 / 255.0,
        }
    }
}

trait PipeExt: Sized {
    fn pipe<F, R>(self, f: F) -> R where F: FnOnce(Self) -> R { f(self) }
}
impl<T> PipeExt for T {}
// #endregion

// #region Parser Context and Errors
#[derive(Clone, Debug)]
pub struct ErrorData {
    pub message: String,
}

pub struct ParserContext {
    pub on_error: Box<dyn FnMut(ErrorData)>,
}

impl Default for ParserContext {
    fn default() -> Self {
        Self {
            on_error: Box::new(|err| {
                eprintln!("[ERROR] {}", err.message);
            }),
        }
    }
}

impl ParserContext {
    pub fn new<F: FnMut(ErrorData) + 'static>(on_error: F) -> Self {
        Self {
            on_error: Box::new(on_error),
        }
    }

    pub fn log_error(&mut self, message: impl Into<String>) {
        (self.on_error)(ErrorData { message: message.into() });
    }
}
// #endregion

// #region Enums
{${_paramEnums}}
// #endregion

// #region Structs
{${_paramStructs}}
// #endregion

// #region Reference Accessors
{${_paramReferenceAccessors}}
// #endregion

// #region Item Kind
{${_paramItemKindEnum}}
// #endregion

// #region Containers
{${_paramTablesStruct}}
{${_paramListsStruct}}
// #endregion

// #region Traits
{${_paramTraits}}
// #endregion

// #region Model Collection and Lookup Traits
pub trait {${_paramPrefix}}Collection<'a> {
    type Output;
    fn get_all_from_root(root: &'a {${_paramPrefix}}Root{${_paramPostfix}}) -> Self::Output;
}

pub trait {${_paramPrefix}}ItemLookup<'a> {
    type Output;
    fn get_from_root(root: &'a {${_paramPrefix}}Root{${_paramPostfix}}, id: &str) -> Option<Self::Output>;
}

pub trait {${_paramPrefix}}ModelItem: Sized {
    fn get_from_root<'a>(root: &'a {${_paramPrefix}}Root{${_paramPostfix}}, id: &str) -> Option<&'a Self>;
    fn get_all_from_root(root: &{${_paramPrefix}}Root{${_paramPostfix}}) -> &[Self];
}

{${_paramModelItemImpls}}
// #endregion

// #region Root
#[derive(Clone, Debug, Default)]
pub struct {${_paramPrefix}}Root{${_paramPostfix}} {
    pub created_by: String,
    pub creation_time: String,
    pub tables: TablesList,
    pub lists: ItemsLists,
    pub path_by_enum: HashMap<String, HashMap<String, String>>,
{${_paramIndexFields}}
}

impl {${_paramPrefix}}Root{${_paramPostfix}} {
    pub fn get<'a, T: {${_paramPrefix}}ItemLookup<'a>>(&'a self, id: &str) -> Option<T::Output> {
        T::get_from_root(self, id)
    }

    pub fn get_or_default<'a, T: {${_paramPrefix}}ItemLookup<'a>>(&'a self, id: &str, default: T::Output) -> T::Output {
        self.get::<T>(id).unwrap_or(default)
    }

    pub fn get_all<'a, T: {${_paramPrefix}}Collection<'a>>(&'a self) -> T::Output {
        T::get_all_from_root(self)
    }

{${_paramGetPathByEnumOverloads}}
    pub fn parse(json_text: &str) -> Result<Self, String> {
        let mut context = ParserContext::default();
        Self::parse_with_context(json_text, &mut context).ok_or_else(|| "Failed to parse ModelRoot".to_string())
    }

    pub fn parse_with_context(json_text: &str, context: &mut ParserContext) -> Option<Self> {
        if json_text.is_empty() {
            context.log_error("json_text is empty");
            return None;
        }

        let json_root: serde_json::Value = match serde_json::from_str(json_text) {
            Ok(v) => v,
            Err(e) => {
                context.log_error(format!("Failed to parse JSON: {e}"));
                return None;
            }
        };

        let mut root = Self {
            created_by: json_root.get("generationUser").and_then(|v| v.as_str()).unwrap_or("").to_string(),
            creation_time: json_root.get("generationDate").and_then(|v| v.as_str()).unwrap_or("").to_string(),
            ..Default::default()
        };

        if let Some(path_by_enum_val) = json_root.get("pathByEnum").and_then(|v| v.as_object()) {
            for (k, v) in path_by_enum_val {
                if let Some(inner_map) = v.as_object() {
                    let mut map = HashMap::new();
                    for (ik, iv) in inner_map {
                        if let Some(s) = iv.as_str() {
                            map.insert(ik.clone(), s.to_string());
                        }
                    }
                    root.path_by_enum.insert(k.clone(), map);
                }
            }
        }

        let tables_val = match json_root.get("tables").and_then(|v| v.as_object()) {
            Some(t) => t,
            None => {
                context.log_error("tables object in JSON is missing");
                return None;
            }
        };

        let mut tables = TablesList::default();
{${_paramTableParsers}}
        root.tables = tables;

{${_paramIndexBuilders}}
        Some(root)
    }
}
// #endregion

// #region Parsing Helper Functions
fn parse_bool(val: Option<&serde_json::Value>) -> bool {
    val.and_then(|v| {
        v.as_bool().or_else(|| v.as_i64().map(|i| i == 1))
    }).unwrap_or(false)
}

fn parse_i32(val: Option<&serde_json::Value>) -> i32 {
    val.and_then(|v| {
        if let Some(i) = v.as_i64() {
            Some(i as i32)
        } else if let Some(s) = v.as_str() {
            s.parse::<i32>().ok()
        } else {
            None
        }
    }).unwrap_or(0)
}

fn parse_i64(val: Option<&serde_json::Value>) -> i64 {
    val.and_then(|v| {
        if let Some(i) = v.as_i64() {
            Some(i)
        } else if let Some(s) = v.as_str() {
            s.parse::<i64>().ok()
        } else {
            None
        }
    }).unwrap_or(0)
}

fn parse_f32(val: Option<&serde_json::Value>) -> f32 {
    val.and_then(|v| {
        if let Some(f) = v.as_f64() {
            Some(f as f32)
        } else if let Some(s) = v.as_str() {
            s.parse::<f32>().ok()
        } else {
            None
        }
    }).unwrap_or(0.0)
}

fn parse_f64(val: Option<&serde_json::Value>) -> f64 {
    val.and_then(|v| {
        if let Some(f) = v.as_f64() {
            Some(f)
        } else if let Some(s) = v.as_str() {
            s.parse::<f64>().ok()
        } else {
            None
        }
    }).unwrap_or(0.0)
}

fn parse_string(val: Option<&serde_json::Value>) -> String {
    val.and_then(|v| v.as_str()).unwrap_or("").to_string()
}

fn parse_color(val: Option<&serde_json::Value>) -> Color {
    Color::from_argb(parse_i64(val))
}

fn parse_vec2(val: Option<&serde_json::Value>) -> Vec2 {
    let s = parse_string(val);
    let parts: Vec<&str> = s.split(';').collect();
    if parts.len() >= 2 {
        Vec2::new(parts[0].parse().unwrap_or(0.0), parts[1].parse().unwrap_or(0.0))
    } else {
        Vec2::ZERO
    }
}

fn parse_ivec2(val: Option<&serde_json::Value>) -> IVec2 {
    let s = parse_string(val);
    let parts: Vec<&str> = s.split(';').collect();
    if parts.len() >= 2 {
        IVec2::new(parts[0].parse().unwrap_or(0), parts[1].parse().unwrap_or(0))
    } else {
        IVec2::ZERO
    }
}

fn parse_vec3(val: Option<&serde_json::Value>) -> Vec3 {
    let s = parse_string(val);
    let parts: Vec<&str> = s.split(';').collect();
    if parts.len() >= 3 {
        Vec3::new(parts[0].parse().unwrap_or(0.0), parts[1].parse().unwrap_or(0.0), parts[2].parse().unwrap_or(0.0))
    } else {
        Vec3::ZERO
    }
}

fn parse_ivec3(val: Option<&serde_json::Value>) -> IVec3 {
    let s = parse_string(val);
    let parts: Vec<&str> = s.split(';').collect();
    if parts.len() >= 3 {
        IVec3::new(parts[0].parse().unwrap_or(0), parts[1].parse().unwrap_or(0), parts[2].parse().unwrap_or(0))
    } else {
        IVec3::ZERO
    }
}

fn parse_vec4(val: Option<&serde_json::Value>) -> Vec4 {
    let s = parse_string(val);
    let parts: Vec<&str> = s.split(';').collect();
    if parts.len() >= 4 {
        Vec4::new(parts[0].parse().unwrap_or(0.0), parts[1].parse().unwrap_or(0.0), parts[2].parse().unwrap_or(0.0), parts[3].parse().unwrap_or(0.0))
    } else {
        Vec4::ZERO
    }
}

fn parse_ivec4(val: Option<&serde_json::Value>) -> IVec4 {
    let s = parse_string(val);
    let parts: Vec<&str> = s.split(';').collect();
    if parts.len() >= 4 {
        IVec4::new(parts[0].parse().unwrap_or(0), parts[1].parse().unwrap_or(0), parts[2].parse().unwrap_or(0), parts[3].parse().unwrap_or(0))
    } else {
        IVec4::ZERO
    }
}

fn parse_rect(val: Option<&serde_json::Value>) -> Rect {
    let s = parse_string(val);
    let parts: Vec<&str> = s.split(';').collect();
    if parts.len() >= 4 {
        let x: f32 = parts[0].parse().unwrap_or(0.0);
        let y: f32 = parts[1].parse().unwrap_or(0.0);
        let w: f32 = parts[2].parse().unwrap_or(0.0);
        let h: f32 = parts[3].parse().unwrap_or(0.0);
        Rect::new(x, y, x + w, y + h)
    } else {
        Rect::from_corners(Vec2::ZERO, Vec2::ZERO)
    }
}

fn parse_irect(val: Option<&serde_json::Value>) -> IRect {
    let s = parse_string(val);
    let parts: Vec<&str> = s.split(';').collect();
    if parts.len() >= 4 {
        let x: i32 = parts[0].parse().unwrap_or(0);
        let y: i32 = parts[1].parse().unwrap_or(0);
        let w: i32 = parts[2].parse().unwrap_or(0);
        let h: i32 = parts[3].parse().unwrap_or(0);
        IRect::new(x, y, x + w, y + h)
    } else {
        IRect::from_corners(IVec2::ZERO, IVec2::ZERO)
    }
}

fn parse_vec<T, F: Fn(&serde_json::Value) -> T>(val: Option<&serde_json::Value>, parse_elem: F) -> Vec<T> {
    val.and_then(|v| v.as_array())
        .map(|arr| arr.iter().map(&parse_elem).collect())
        .unwrap_or_default()
}

fn parse_hash_map<T, F: Fn(&serde_json::Value) -> T>(val: Option<&serde_json::Value>, parse_elem: F) -> HashMap<String, T> {
    val.and_then(|v| v.as_object())
        .map(|obj| obj.iter().map(|(k, v)| (k.clone(), parse_elem(v))).collect())
        .unwrap_or_default()
}
// #endregion
''';
}
