// ignore_for_file: unnecessary_brace_in_string_interps

import 'package:darq/darq.dart';
import 'package:gceditor/model/db/class_field_description_data_info.dart';
import 'package:gceditor/model/db/class_meta_entity.dart';
import 'package:gceditor/model/db/class_meta_entity_enum.dart';
import 'package:gceditor/model/db/class_meta_field_description.dart';
import 'package:gceditor/model/db/db_model.dart';
import 'package:gceditor/model/db/db_model_shared.dart';
import 'package:gceditor/model/db/generator_gdscript.dart';
import 'package:gceditor/utils/utils.dart';

import 'generators_job.dart';

class GeneratorGdscriptRunner extends BaseGeneratorRunner<GeneratorGdscript> with OutputFolderSaver, FilesComparer {
  static final _newLineRegExp = RegExp(r'[\r\n]+');
  static const _indent = '\t';
  static const _defaultNewLine = '\n';
  static const _itemsListSuffix = 'ItemsList';

  static const _paramDate = 'date';
  static const _paramUser = 'user';
  static const _paramPrefix = 'prefix';
  static const _paramPostfix = 'postfix';
  static const _paramEnums = 'enums';
  static const _paramClasses = 'classes';
  static const _paramItemsLists = 'itemsLists';
  static const _paramListInstantiate = 'listInstantiate';
  static const _paramAssignValueCases = 'assignValueCases';
  static const _paramMaxStructDepth = 'maxStructDepth';
  static const _paramTableClassMap = 'tableClassMap';
  static const _paramListItemsListsAssignment = 'listItemsListsAssignment';
  static const _paramListItemsListsDeclarations = 'listItemsListsDeclarations';
  static const _paramTablesListDeclarations = 'tablesListDeclarations';
  static const _paramTablesListAssignment = 'tablesListAssignment';
  static const _paramGetPathByEnumOverloads = 'getPathByEnumOverloads';
  static const _paramTypedGetters = 'typedGetters';

  @override
  Future<GeneratorResult> execute(String outputFolder, DbModel model, GeneratorGdscript data, GeneratorAdditionalInformation additionalInfo) async {
    try {
      final result = _rootTemplate.format({
        _paramDate: additionalInfo.date,
        _paramUser: additionalInfo.user,
        _paramPrefix: data.prefix,
        _paramPostfix: data.postfix,
        _paramEnums: _getEnums(model, data),
        _paramClasses: _getClasses(model, data),
        _paramItemsLists: _getItemsLists(model, data),
        _paramListInstantiate: _getListInstantiate(model, data),
        _paramAssignValueCases: _getAssignValuesCases(model, data),
        _paramMaxStructDepth: _getMaxStructDepth(model, 3),
        _paramTableClassMap: _getTableClassMap(model, data),
        _paramListItemsListsAssignment: _getListItemsListAssignment(model, data),
        _paramListItemsListsDeclarations: _getListItemsListsDeclarations(model, data),
        _paramTablesListDeclarations: _getTablesListDeclarations(model, data),
        _paramTablesListAssignment: _getTablesListAssignment(model, data),
        _paramGetPathByEnumOverloads: _getPathByEnumOverloads(model, data),
        _paramTypedGetters: _getTypedGetters(model, data),
      });

      final previousResult = await readFromFile(
        outputFolder: outputFolder,
        fileName: data.fileName,
        fileExtension: data.fileExtension,
      );

      if (!resultChanged(result, previousResult, '# This file was autogenerated')) {
        return GeneratorResult.success();
      }

      final saveError = await saveToFile(
        outputFolder: outputFolder,
        fileName: data.fileName,
        fileExtension: data.fileExtension,
        data: result,
      );

      if (saveError != null) {
        return GeneratorResult.error(saveError);
      }
    } catch (e) {
      return GeneratorResult.error(e.toString());
    }

    return GeneratorResult.success();
  }

  static const _gdscriptReservedAndNative = {
    'if',
    'elif',
    'else',
    'for',
    'while',
    'match',
    'break',
    'continue',
    'pass',
    'return',
    'class',
    'class_name',
    'extends',
    'is',
    'as',
    'self',
    'tool',
    'signal',
    'func',
    'static',
    'const',
    'enum',
    'var',
    'onready',
    'export',
    'setget',
    'breakpoint',
    'preload',
    'await',
    'yield',
    'assert',
    'void',
    'PI',
    'TAU',
    'INF',
    'NAN',
    'Input',
    'Image',
    'Texture',
    'Texture2D',
    'Material',
    'Shader',
    'Mesh',
    'Font',
    'Animation',
    'AudioStream',
    'AudioEffect',
    'CollisionShape2D',
    'CollisionShape3D',
    'Camera2D',
    'Camera3D',
    'Sprite2D',
    'Sprite3D',
    'CanvasItem',
    'CanvasLayer',
    'Window',
    'Viewport',
    'Control',
    'Node2D',
    'Node3D',
    'Timer',
    'Tween',
    'File',
    'Dir',
    'Path',
    'Shape',
    'Theme',
    'Curve',
    'Gradient',
    'Light2D',
    'Light3D',
    'PackedScene',
    'Script',
    'World2D',
    'World3D',
    'Environment',
    'Node',
    'Resource',
    'Object',
    'OS',
    'Engine',
    'Time',
    'JSON',
    'RegEx',
    'FileAccess',
    'DirAccess',
    'Array',
    'Dictionary',
    'Color',
    'String',
    'RefCounted',
    'DisplayServer',
    'RenderingServer',
    'AudioServer',
    'PhysicsServer2D',
    'PhysicsServer3D',
    'NavigationServer2D',
    'NavigationServer3D',
    'TextServer',
    'CameraServer',
    'XRServer',
    'IP',
    'Geometry2D',
    'Geometry3D',
    'Marshalls',
    'TranslationServer',
    'Performance',
    'ThemeDB',
    'WorkerThreadPool',
    'ClassDB',
    'ResourceLoader',
    'ResourceSaver',
    'MainLoop',
    'SceneTree',
    'Vector2',
    'Vector2i',
    'Vector3',
    'Vector3i',
    'Vector4',
    'Vector4i',
    'Rect2',
    'Rect2i',
    'Transform2D',
    'Transform3D',
    'Plane',
    'Quaternion',
    'AABB',
    'Basis',
    'Projection',
    'StringName',
    'NodePath',
    'RID',
    'Callable',
    'Signal',
    'Mutex',
    'Semaphore',
    'Thread',
    'StreamPeer',
    'Crypto',
    'ConfigFile',
    'StyleBox',
  };

  static String _escapeIdentifier(String id) {
    if (_gdscriptReservedAndNative.contains(id)) {
      return '${id}_';
    }
    return id;
  }

  String _getEnums(DbModel model, GeneratorGdscript data) {
    final sb = StringBuffer();
    for (final enumEntity in model.cache.allEnums) {
      if (enumEntity.description.isNotEmpty) {
        sb.writeln('## ${enumEntity.description}');
      }
      final enumName = '${data.prefix}${enumEntity.id}${data.postfix}';
      sb.writeln('enum $enumName {');
      for (var i = 0; i < enumEntity.values.length; i++) {
        final val = enumEntity.values[i];
        final escapedId = _escapeIdentifier(val.id);
        sb.writeln('${_indent}$escapedId = $i,');
      }
      sb.writeln('}');
      sb.writeln();
    }
    return sb.toString();
  }

  String _getClasses(DbModel model, GeneratorGdscript data) {
    final items = <String>[];
    // Sort base classes before derived classes
    final allClassesSorted = model.cache.allClasses.orderBy((e) => model.cache.getParentClasses(e).length).toList();

    for (final classEntity in allClassesSorted) {
      if (classEntity.classType == ClassType.undefined || classEntity.classType == ClassType.interface) {
        continue;
      }

      final isValueType = classEntity.classType == ClassType.valueType;
      final parentClass = classEntity.parent != null && classEntity.parent!.isNotEmpty
          ? '${data.prefix}${classEntity.parent}${data.postfix}'
          : 'Base${data.prefix}Item${data.postfix}';

      final properties = <String>[];
      final cloneProperties = <String>[];

      for (final field in classEntity.fields) {
        final propType = _getPropertyType(field, data, model);
        final defaultVal = _getDefaultPropertyValue(field, data, model);
        final escapedId = _escapeIdentifier(field.id);
        properties.add('${_indent}var $escapedId: $propType = $defaultVal');
      }

      for (final field in model.cache.getAllFields(classEntity)) {
        final escapedId = _escapeIdentifier(field.id);
        if (field.typeInfo.type == ClassFieldType.list ||
            field.typeInfo.type == ClassFieldType.set ||
            field.typeInfo.type == ClassFieldType.listInline) {
          cloneProperties.add('${_indent}${_indent}result.$escapedId = $escapedId.duplicate(true)');
        } else if (field.typeInfo.type == ClassFieldType.dictionary) {
          cloneProperties.add('${_indent}${_indent}result.$escapedId = $escapedId.duplicate(true)');
        } else {
          cloneProperties.add('${_indent}${_indent}result.$escapedId = $escapedId');
        }
      }

      final typeNames = _getParentTypeNames(model, data, classEntity);
      final typeNamesLiteral = typeNames.map((e) => '"$e"').join(', ');

      final className = '${data.prefix}${classEntity.id}${data.postfix}';
      final sb = StringBuffer();
      if (classEntity.description.isNotEmpty) {
        sb.writeln('## ${classEntity.description}');
      }
      sb.writeln('class $className extends $parentClass:');
      if (isValueType) {
        sb.writeln('${_indent}func is_value_type() -> bool:');
        sb.writeln('${_indent}${_indent}return true');
      }
      if (properties.isEmpty) {
        sb.writeln('${_indent}pass');
      } else {
        for (final p in properties) {
          sb.writeln(p);
        }
      }
      sb.writeln();
      sb.writeln('${_indent}func get_type_names() -> Array:');
      sb.writeln('${_indent}${_indent}return [$typeNamesLiteral]');
      sb.writeln();
      sb.writeln('${_indent}func clone() -> $className:');
      sb.writeln('${_indent}${_indent}var result = $className.new()');
      sb.writeln('${_indent}${_indent}result.id = id');
      sb.writeln('${_indent}${_indent}result.is_global = is_global');
      for (final cp in cloneProperties) {
        sb.writeln(cp);
      }
      sb.writeln('${_indent}${_indent}return result');
      sb.writeln();
      sb.writeln('${_indent}func _to_string() -> String:');
      sb.writeln('${_indent}${_indent}return "$className {id: %s}" % id');
      sb.writeln();

      items.add(sb.toString());
    }

    return items.join(_defaultNewLine);
  }

  Set<String> _getParentTypeNames(DbModel model, GeneratorGdscript data, ClassMetaEntity classEntity) {
    final typeNames = <String>{};

    // 1. Current class
    typeNames.add(classEntity.id);
    typeNames.add('${data.prefix}${classEntity.id}${data.postfix}');

    // 2. Parent classes (if reference type)
    if (classEntity.classType != ClassType.valueType) {
      final parentClasses = model.cache.getParentClasses(classEntity);
      for (final parent in parentClasses) {
        typeNames.add(parent.id);
        typeNames.add('${data.prefix}${parent.id}${data.postfix}');
      }
    }

    // 3. All interfaces (direct and inherited from parent classes and parent interfaces)
    final allInterfaces = _getAllInterfaces(model, classEntity);
    for (final iface in allInterfaces) {
      typeNames.add(iface.id);
      typeNames.add('${data.prefix}${iface.id}${data.postfix}');
    }

    return typeNames;
  }

  Set<ClassMetaEntity> _getAllInterfaces(DbModel model, ClassMetaEntity classEntity) {
    final result = <ClassMetaEntity>{};

    void collectFrom(ClassMetaEntity entity) {
      final ifaces = model.cache.getParentInterfaces(entity);
      for (final iface in ifaces) {
        result.add(iface);
      }
    }

    collectFrom(classEntity);

    if (classEntity.classType != ClassType.valueType) {
      final parentClasses = model.cache.getParentClasses(classEntity);
      for (final parent in parentClasses) {
        collectFrom(parent);
      }
    }

    return result;
  }

  String _getPropertyType(ClassMetaFieldDescription field, GeneratorGdscript data, [DbModel? model]) {
    switch (field.typeInfo.type) {
      case ClassFieldType.bool:
        return 'bool';
      case ClassFieldType.int:
      case ClassFieldType.long:
      case ClassFieldType.date:
      case ClassFieldType.duration:
        return 'int';
      case ClassFieldType.float:
      case ClassFieldType.double:
        return 'float';
      case ClassFieldType.string:
      case ClassFieldType.text:
      case ClassFieldType.undefined:
        return 'String';
      case ClassFieldType.color:
        return 'Color';
      case ClassFieldType.vector2:
        return 'Vector2';
      case ClassFieldType.vector2Int:
        return 'Vector2i';
      case ClassFieldType.vector3:
        return 'Vector3';
      case ClassFieldType.vector3Int:
        return 'Vector3i';
      case ClassFieldType.vector4:
        return 'Vector4';
      case ClassFieldType.vector4Int:
        return 'Vector4i';
      case ClassFieldType.rectangle:
        return 'Rect2';
      case ClassFieldType.rectangleInt:
        return 'Rect2i';
      case ClassFieldType.reference:
        if (model != null && field.typeInfo.classId != null) {
          final classEntity = model.cache.getEntity(field.typeInfo.classId!);
          if (classEntity is ClassMetaEntityEnum) {
            final enumName = '${data.prefix}${classEntity.id}${data.postfix}';
            return enumName;
          }
          if (classEntity != null) {
            final className = '${data.prefix}${classEntity.id}${data.postfix}';
            return className;
          }
        }
        return 'RefCounted';
      case ClassFieldType.list:
      case ClassFieldType.listInline:
      case ClassFieldType.set:
        return 'Array';
      case ClassFieldType.dictionary:
        return 'Dictionary';
    }
  }

  String _getDefaultPropertyValue(ClassMetaFieldDescription field, GeneratorGdscript data, [DbModel? model]) {
    switch (field.typeInfo.type) {
      case ClassFieldType.bool:
        return 'false';
      case ClassFieldType.int:
      case ClassFieldType.long:
      case ClassFieldType.date:
      case ClassFieldType.duration:
        return '0';
      case ClassFieldType.float:
      case ClassFieldType.double:
        return '0.0';
      case ClassFieldType.string:
      case ClassFieldType.text:
      case ClassFieldType.undefined:
        return '""';
      case ClassFieldType.color:
        return 'Color(0, 0, 0, 1)';
      case ClassFieldType.vector2:
        return 'Vector2.ZERO';
      case ClassFieldType.vector2Int:
        return 'Vector2i.ZERO';
      case ClassFieldType.vector3:
        return 'Vector3.ZERO';
      case ClassFieldType.vector3Int:
        return 'Vector3i.ZERO';
      case ClassFieldType.vector4:
        return 'Vector4.ZERO';
      case ClassFieldType.vector4Int:
        return 'Vector4i.ZERO';
      case ClassFieldType.rectangle:
        return 'Rect2()';
      case ClassFieldType.rectangleInt:
        return 'Rect2i()';
      case ClassFieldType.reference:
        if (model != null && field.typeInfo.classId != null) {
          final classEntity = model.cache.getEntity(field.typeInfo.classId!);
          if (classEntity is ClassMetaEntityEnum) {
            final enumName = '${data.prefix}${classEntity.id}${data.postfix}';
            final firstVal = classEntity.values.isNotEmpty ? '$enumName.${_escapeIdentifier(classEntity.values.first.id)}' : '0';
            return firstVal;
          }
        }
        return 'null';
      case ClassFieldType.list:
      case ClassFieldType.listInline:
      case ClassFieldType.set:
        return '[]';
      case ClassFieldType.dictionary:
        return '{}';
    }
  }

  String _getItemsLists(DbModel model, GeneratorGdscript data) {
    final sb = StringBuffer();
    for (final classEntity in model.cache.allClasses) {
      if (classEntity.exportList != true) continue;
      final className = '${data.prefix}${classEntity.id}${data.postfix}';
      final listClassName = '$className${MetaEntityType.Class.name}$_itemsListSuffix';

      final thisAndParentClasses = model.cache.getImplementingClasses(classEntity).concat([classEntity]).map((e) => e.id).toSet();
      final allItems =
          model.cache.allDataTables.where((element) => thisAndParentClasses.contains(element.classId)).toMap((e) => MapEntry(e.classId, e.rows));

      sb.writeln('class $listClassName extends RefCounted:');
      var hasProperties = false;
      for (final kvp in allItems.entries) {
        for (final row in kvp.value) {
          if (row.id.isNotEmpty) {
            final escapedRowId = _escapeIdentifier(row.id);
            sb.writeln('${_indent}var $escapedRowId: $className = null');
            hasProperties = true;
          }
        }
      }
      if (!hasProperties) {
        sb.writeln('${_indent}pass');
      }
      sb.writeln();
      sb.writeln('${_indent}func _init(all_items: Dictionary):');
      var hasInit = false;
      for (final kvp in allItems.entries) {
        for (final row in kvp.value) {
          if (row.id.isNotEmpty) {
            final escapedRowId = _escapeIdentifier(row.id);
            sb.writeln('${_indent}${_indent}if all_items.has("${row.id}"):');
            sb.writeln('${_indent}${_indent}${_indent}$escapedRowId = all_items["${row.id}"]');
            hasInit = true;
          }
        }
      }
      if (!hasInit) {
        sb.writeln('${_indent}${_indent}pass');
      }
      sb.writeln();
    }
    return sb.toString();
  }

  String _getListInstantiate(DbModel model, GeneratorGdscript data) {
    final sb = StringBuffer();
    for (final classEntity in model.cache.allClasses) {
      if (classEntity.classType == ClassType.undefined || classEntity.classType == ClassType.interface) {
        continue;
      }
      final className = '${data.prefix}${classEntity.id}${data.postfix}';
      sb.writeln('${_indent}${_indent}"${classEntity.id}":');
      sb.writeln('${_indent}${_indent}${_indent}var inst = $className.new()');
      sb.writeln('${_indent}${_indent}${_indent}inst.id = id');
      sb.writeln('${_indent}${_indent}${_indent}inst.is_global = is_global');
      sb.writeln('${_indent}${_indent}${_indent}return inst');
    }
    return sb.toString();
  }

  String _getTableClassMap(DbModel model, GeneratorGdscript data) {
    final sb = StringBuffer();
    for (final table in model.cache.allDataTables) {
      sb.writeln('${_indent}${_indent}"${table.id}": return "${table.classId}"');
    }
    return sb.toString();
  }

  String _getAssignValuesCases(DbModel model, GeneratorGdscript data) {
    final sb = StringBuffer();
    for (final classEntity in model.cache.allClasses) {
      if (classEntity.classType == ClassType.undefined || classEntity.classType == ClassType.interface) {
        continue;
      }
      final className = '${data.prefix}${classEntity.id}${data.postfix}';
      sb.writeln('${_indent}if instance is $className:');
      final allFields = model.cache.getAllFields(classEntity);
      if (allFields.isEmpty) {
        sb.writeln('${_indent}${_indent}pass');
      } else {
        for (final field in allFields) {
          final parseExpr = _getAssignValueFunction(model, data, field);
          final escapedId = _escapeIdentifier(field.id);
          sb.writeln('${_indent}${_indent}if values_by_id.has("${field.id}"):');
          sb.writeln('${_indent}${_indent}${_indent}instance.$escapedId = $parseExpr');
        }
      }
    }
    return sb.toString();
  }

  String _getAssignValueFunction(DbModel model, GeneratorGdscript data, ClassMetaFieldDescription field) {
    final rawVal = 'values_by_id["${field.id}"]';
    switch (field.typeInfo.type) {
      case ClassFieldType.bool:
        return '_parse_bool($rawVal, context)';
      case ClassFieldType.int:
      case ClassFieldType.long:
      case ClassFieldType.date:
      case ClassFieldType.duration:
        return '_parse_int($rawVal, context)';
      case ClassFieldType.float:
      case ClassFieldType.double:
        return '_parse_float($rawVal, context)';
      case ClassFieldType.string:
      case ClassFieldType.text:
      case ClassFieldType.undefined:
        return '_parse_string($rawVal)';
      case ClassFieldType.color:
        return '_parse_color($rawVal, context)';
      case ClassFieldType.vector2:
        return '_parse_vector2($rawVal, context)';
      case ClassFieldType.vector2Int:
        return '_parse_vector2i($rawVal, context)';
      case ClassFieldType.vector3:
        return '_parse_vector3($rawVal, context)';
      case ClassFieldType.vector3Int:
        return '_parse_vector3i($rawVal, context)';
      case ClassFieldType.vector4:
        return '_parse_vector4($rawVal, context)';
      case ClassFieldType.vector4Int:
        return '_parse_vector4i($rawVal, context)';
      case ClassFieldType.rectangle:
        return '_parse_rect2($rawVal, context)';
      case ClassFieldType.rectangleInt:
        return '_parse_rect2i($rawVal, context)';
      case ClassFieldType.reference:
        final classEntity = model.cache.getEntity(field.typeInfo.classId!);
        if (classEntity is ClassMetaEntityEnum) {
          final enumName = '${data.prefix}${classEntity.id}${data.postfix}';
          final firstVal = classEntity.values.isNotEmpty ? '$enumName.${_escapeIdentifier(classEntity.values.first.id)}' : '0';
          return '$enumName.get(_parse_string($rawVal), $firstVal)';
        }
        return '_parse_reference($rawVal, objects_by_ids, context)';
      case ClassFieldType.list:
      case ClassFieldType.set:
        final innerParser = _getSimpleValueLambda(model, data, field.valueTypeInfo!);
        return '_parse_list($rawVal, $innerParser, context)';
      case ClassFieldType.listInline:
        final inlineClassId = field.valueTypeInfo!.classId!;
        return '_parse_list_inline($rawVal, func(item_dict): return _assign_values(_get_new_instance("$inlineClassId", item_dict, instance.id, context), objects_by_ids, item_dict, context))';
      case ClassFieldType.dictionary:
        final keyParser = _getSimpleValueLambda(model, data, field.keyTypeInfo!);
        final valParser = _getSimpleValueLambda(model, data, field.valueTypeInfo!);
        return '_parse_dictionary($rawVal, $keyParser, $valParser, context)';
    }
  }

  String _getSimpleValueLambda(DbModel model, GeneratorGdscript data, ClassFieldDescriptionDataInfo type) {
    switch (type.type) {
      case ClassFieldType.bool:
        return 'func(v): return _parse_bool(v, context)';
      case ClassFieldType.int:
      case ClassFieldType.long:
      case ClassFieldType.date:
      case ClassFieldType.duration:
        return 'func(v): return _parse_int(v, context)';
      case ClassFieldType.float:
      case ClassFieldType.double:
        return 'func(v): return _parse_float(v, context)';
      case ClassFieldType.string:
      case ClassFieldType.text:
      case ClassFieldType.undefined:
        return 'func(v): return _parse_string(v)';
      case ClassFieldType.color:
        return 'func(v): return _parse_color(v, context)';
      case ClassFieldType.vector2:
        return 'func(v): return _parse_vector2(v, context)';
      case ClassFieldType.vector2Int:
        return 'func(v): return _parse_vector2i(v, context)';
      case ClassFieldType.vector3:
        return 'func(v): return _parse_vector3(v, context)';
      case ClassFieldType.vector3Int:
        return 'func(v): return _parse_vector3i(v, context)';
      case ClassFieldType.vector4:
        return 'func(v): return _parse_vector4(v, context)';
      case ClassFieldType.vector4Int:
        return 'func(v): return _parse_vector4i(v, context)';
      case ClassFieldType.rectangle:
        return 'func(v): return _parse_rect2(v, context)';
      case ClassFieldType.rectangleInt:
        return 'func(v): return _parse_rect2i(v, context)';
      case ClassFieldType.reference:
        final classEntity = model.cache.getEntity(type.classId!);
        if (classEntity is ClassMetaEntityEnum) {
          final enumName = '${data.prefix}${classEntity.id}${data.postfix}';
          final firstVal = classEntity.values.isNotEmpty ? '$enumName.${_escapeIdentifier(classEntity.values.first.id)}' : '0';
          return 'func(v): return $enumName.get(_parse_string(v), $firstVal)';
        }
        return 'func(v): return _parse_reference(v, objects_by_ids, context)';
      default:
        return 'func(v): return v';
    }
  }

  String _getListItemsListsDeclarations(DbModel model, GeneratorGdscript data) {
    final sb = StringBuffer();
    for (final classEntity in model.cache.allClasses) {
      if (classEntity.exportList != true) continue;
      final className = '${data.prefix}${classEntity.id}${data.postfix}';
      final listClassName = '$className${MetaEntityType.Class.name}$_itemsListSuffix';
      sb.writeln('${_indent}var ${classEntity.id.toLowerCase()}: $listClassName = null');
    }
    return sb.toString();
  }

  String _getListItemsListAssignment(DbModel model, GeneratorGdscript data) {
    final sb = StringBuffer();
    for (final classEntity in model.cache.allClasses) {
      if (classEntity.exportList != true) continue;
      final className = '${data.prefix}${classEntity.id}${data.postfix}';
      final listClassName = '$className${MetaEntityType.Class.name}$_itemsListSuffix';
      sb.writeln('${_indent}${_indent}${classEntity.id.toLowerCase()} = $listClassName.new(all_items)');
    }
    if (sb.isEmpty) {
      sb.writeln('${_indent}${_indent}pass');
    }
    return sb.toString();
  }

  String _getTablesListDeclarations(DbModel model, GeneratorGdscript data) {
    final sb = StringBuffer();
    for (final table in model.cache.allDataTables) {
      sb.writeln('${_indent}var ${table.id}: Array = []');
    }
    return sb.toString();
  }

  String _getTablesListAssignment(DbModel model, GeneratorGdscript data) {
    final sb = StringBuffer();
    for (final table in model.cache.allDataTables) {
      sb.writeln('${_indent}${_indent}if tables.has("${table.id}"):');
      sb.writeln('${_indent}${_indent}${_indent}${table.id} = tables["${table.id}"]');
    }
    if (sb.isEmpty) {
      sb.writeln('${_indent}${_indent}pass');
    }
    return sb.toString();
  }

  String _getPathByEnumOverloads(DbModel model, GeneratorGdscript data) {
    final sb = StringBuffer();
    for (final enumEntity in model.cache.allEnums) {
      if (enumEntity.autoByFile) {
        final enumName = '${data.prefix}${enumEntity.id}${data.postfix}';
        sb.writeln('func get_path_by_${enumEntity.id.toLowerCase()}(value: $enumName) -> String:');
        sb.writeln('${_indent}var str_val = $enumName.find_key(value)');
        sb.writeln('${_indent}if str_val == null:');
        sb.writeln('${_indent}${_indent}push_error("Invalid enum value: %s" % str(value))');
        sb.writeln('${_indent}${_indent}return ""');
        sb.writeln('${_indent}if path_by_enum != null and path_by_enum.has("${enumEntity.id}"):');
        sb.writeln('${_indent}${_indent}var enum_map = path_by_enum["${enumEntity.id}"]');
        sb.writeln('${_indent}${_indent}if enum_map.has(str_val):');
        sb.writeln('${_indent}${_indent}${_indent}return enum_map[str_val]');
        sb.writeln('${_indent}push_error("Path not found in JSON data for enum value: %s" % str_val)');
        sb.writeln('${_indent}return ""');
        sb.writeln();
      }
    }
    return sb.toString();
  }

  String _getTypedGetters(DbModel model, GeneratorGdscript data) {
    final sb = StringBuffer();
    for (final classEntity in model.cache.allClasses) {
      if (classEntity.classType == ClassType.undefined || classEntity.classType == ClassType.interface) {
        continue;
      }
      final className = '${data.prefix}${classEntity.id}${data.postfix}';
      final lowerName = classEntity.id.toLowerCase();
      sb.writeln('func get_$lowerName(id: String) -> $className:');
      sb.writeln('${_indent}if all_items.has(id):');
      sb.writeln('${_indent}${_indent}var item = all_items[id]');
      sb.writeln('${_indent}${_indent}if item is $className:');
      sb.writeln('${_indent}${_indent}${_indent}return item');
      sb.writeln('${_indent}return null');
      sb.writeln();
    }
    return sb.toString();
  }

  int _getMaxStructDepth(DbModel model, int defaultDepth) {
    int depth = defaultDepth;
    for (final classEntity in model.cache.allClasses) {
      if (classEntity.classType == ClassType.valueType) {
        depth = 4;
        break;
      }
    }
    return depth;
  }

  final String _rootTemplate = '''# This file was autogenerated via gceditor https://github.com/kennelken/gceditor_fl
# {${_paramDate}}
# by {${_paramUser}}
#
# Usage:
# var config = {${_paramPrefix}}Root{${_paramPostfix}}.parse(json_text)
# use 'config' as a source of config data

class_name {${_paramPrefix}}Root{${_paramPostfix}} extends RefCounted

#region Error and Context Classes
class ErrorData extends RefCounted:
	var entity: RefCounted
	var message: String
	func _init(p_entity: RefCounted = null, p_message: String = ""):
		entity = p_entity
		message = p_message

class ParserContext extends RefCounted:
	var on_error: Callable
	func _init(p_on_error: Callable = Callable()):
		on_error = p_on_error

	func log_error(p_message: String, p_entity: RefCounted = null) -> void:
		if on_error.is_valid():
			on_error.call(ErrorData.new(p_entity, p_message))
		else:
			push_error(p_message)
#endregion

#region Base Item
class Base{${_paramPrefix}}Item{${_paramPostfix}} extends RefCounted:
	var id: String = ""
	var is_global: bool = false
	func is_value_type() -> bool:
		return false
	func get_type_names() -> Array:
		return []
	func _on_parsed(root: RefCounted, cache: RefCounted) -> void:
		pass
#endregion

#region Enums
{${_paramEnums}}
#endregion

#region Classes Definitions
{${_paramClasses}}
#endregion

#region Items Lists
{${_paramItemsLists}}
#endregion

#region Containers
class ItemsLists extends RefCounted:
{${_paramListItemsListsDeclarations}}
	func _init(all_items: Dictionary):
{${_paramListItemsListsAssignment}}

class TablesList extends RefCounted:
{${_paramTablesListDeclarations}}
	func _init(tables: Dictionary):
{${_paramTablesListAssignment}}

class CacheRoot extends RefCounted:
	var _caches: Dictionary = {}
	func get_cache(key: Variant, create_func: Callable) -> Variant:
		if not _caches.has(key):
			_caches[key] = create_func.call()
		return _caches[key]
#endregion

#region Root Properties
var created_by: String = ""
var creation_time: String = ""
var all_items: Dictionary = {}
var all_items_by_type: Dictionary = {}
var lists: ItemsLists = null
var tables: TablesList = null
var path_by_enum: Dictionary = {}

static var instance: {${_paramPrefix}}Root{${_paramPostfix}} = null
#endregion

#region Retrieval Methods
func get_item(id: String) -> Base{${_paramPrefix}}Item{${_paramPostfix}}:
	if all_items.has(id):
		return all_items[id]
	return null

func get_item_or_default(id: String, default_value: Base{${_paramPrefix}}Item{${_paramPostfix}} = null) -> Base{${_paramPrefix}}Item{${_paramPostfix}}:
	if all_items.has(id):
		return all_items[id]
	return default_value

func get_all(type_name: String) -> Array:
	if all_items_by_type.has(type_name):
		return all_items_by_type[type_name]
	return []

{${_paramTypedGetters}}
{${_paramGetPathByEnumOverloads}}
#endregion

#region Initialization
func initialize(items: Array) -> void:
	{${_paramPrefix}}Root{${_paramPostfix}}.instance = self
	all_items.clear()
	all_items_by_type.clear()

	for item in items:
		if item == null:
			continue
		all_items[item.id] = item
		if item.has_method("get_type_names"):
			for type_name in item.get_type_names():
				if not all_items_by_type.has(type_name):
					all_items_by_type[type_name] = []
				all_items_by_type[type_name].append(item)

	lists = ItemsLists.new(all_items)
#endregion

#region Parser
static var _inline_items_counter: Dictionary = {}

static func _get_inline_row_id(owner_id: String) -> String:
	var count = _inline_items_counter.get(owner_id, 0)
	_inline_items_counter[owner_id] = count + 1
	return "%s#%03d" % [owner_id, count]

static func parse(json_text: String, root: {${_paramPrefix}}Root{${_paramPostfix}} = null, on_error: Callable = Callable(), context: ParserContext = null) -> {${_paramPrefix}}Root{${_paramPostfix}}:
	if context == null:
		context = ParserContext.new(on_error)
	elif on_error.is_valid() and not context.on_error.is_valid():
		context.on_error = on_error

	if json_text.is_empty():
		context.log_error("json_text is empty")
		return root

	var parsed_json = JSON.parse_string(json_text)
	if parsed_json == null or not (parsed_json is Dictionary):
		context.log_error("Failed to parse JSON string or root is not an object")
		return root

	var json_root: Dictionary = parsed_json
	var json_tables = json_root.get("tables", {})
	if not (json_tables is Dictionary):
		context.log_error("tables in JSON root is missing or invalid")
		return root

	var objects_by_ids: Dictionary = {}
	var values_by_ids: Dictionary = {}
	var tables_dict: Dictionary = {}

	for table_name in json_tables.keys():
		var class_name_str = _get_table_class(table_name, context)
		if class_name_str.is_empty():
			continue

		var list_items = json_tables[table_name]
		if not (list_items is Array):
			continue

		var table_items: Array = []
		for item in list_items:
			if not (item is Dictionary):
				continue
			var inst = _get_new_instance(class_name_str, item, "", context)
			if inst == null:
				continue
			objects_by_ids[inst.id] = inst
			values_by_ids[inst.id] = item
			table_items.append(inst)

		tables_dict[table_name] = table_items

	var all_structs: Array[String] = []
	var all_classes: Array[String] = []
	for obj_id in objects_by_ids.keys():
		var item = objects_by_ids[obj_id]
		if item.is_value_type():
			all_structs.append(obj_id)
		else:
			all_classes.append(obj_id)

	var max_depth = {${_paramMaxStructDepth}}
	for d in range(max_depth):
		for obj_id in all_structs:
			objects_by_ids[obj_id] = _assign_values(objects_by_ids[obj_id], objects_by_ids, values_by_ids.get(obj_id, {}), context)

	for obj_id in all_classes:
		objects_by_ids[obj_id] = _assign_values(objects_by_ids[obj_id], objects_by_ids, values_by_ids.get(obj_id, {}), context)

	if root == null:
		root = {${_paramPrefix}}Root{${_paramPostfix}}.new()

	root.created_by = str(json_root.get("generationUser", ""))
	root.creation_time = str(json_root.get("generationDate", ""))
	root.initialize(objects_by_ids.values())
	root.tables = TablesList.new(tables_dict)
	root.path_by_enum = json_root.get("pathByEnum", {})

	var cache = CacheRoot.new()
	for obj_id in all_classes:
		var inst = objects_by_ids[obj_id]
		if inst != null and inst.has_method("_on_parsed"):
			inst._on_parsed(root, cache)

	_inline_items_counter.clear()
	return root

static func _get_new_instance(class_name_str: String, item: Dictionary, owner_id: String, context: ParserContext) -> RefCounted:
	var id: String = ""
	var is_global: bool = false
	if item != null and item.has("id"):
		id = str(item["id"])
		is_global = true
	else:
		id = _get_inline_row_id(owner_id)

	match class_name_str:
{${_paramListInstantiate}}
		_:
			context.log_error("Cannot create instance of unknown class '%s'" % class_name_str)
			return null

static func _get_table_class(table_id: String, context: ParserContext) -> String:
	match table_id:
{${_paramTableClassMap}}
		_:
			context.log_error("Unknown table '%s'" % table_id)
			return ""

static func _assign_values(instance: RefCounted, objects_by_ids: Dictionary, values_by_id: Dictionary, context: ParserContext) -> RefCounted:
	if instance == null:
		return null
{${_paramAssignValueCases}}
	return instance

static func _parse_bool(val: Variant, context: ParserContext) -> bool:
	return _parse_int(val, context) == 1

static func _parse_int(val: Variant, context: ParserContext) -> int:
	if val == null:
		return 0
	return int(val)

static func _parse_float(val: Variant, context: ParserContext) -> float:
	if val == null:
		return 0.0
	return float(val)

static func _parse_string(val: Variant) -> String:
	if val == null:
		return ""
	return str(val)

static func _parse_reference(val: Variant, objects_by_ids: Dictionary, context: ParserContext) -> RefCounted:
	var id_str = _parse_string(val)
	if id_str.is_empty():
		return null
	if objects_by_ids.has(id_str):
		return objects_by_ids[id_str]
	context.log_error("Could not find object with id '%s'" % id_str)
	return null

static func _parse_color(val: Variant, context: ParserContext) -> Color:
	var argb = _parse_int(val, context)
	var a = ((argb >> 24) & 0xFF) / 255.0
	var r = ((argb >> 16) & 0xFF) / 255.0
	var g = ((argb >> 8) & 0xFF) / 255.0
	var b = (argb & 0xFF) / 255.0
	return Color(r, g, b, a)

static func _parse_vector2(val: Variant, context: ParserContext) -> Vector2:
	var str_val = _parse_string(val)
	if str_val.is_empty():
		return Vector2.ZERO
	var parts = str_val.split(";")
	if parts.size() < 2:
		context.log_error("Failed to parse Vector2 from '%s'" % str_val)
		return Vector2.ZERO
	return Vector2(float(parts[0]), float(parts[1]))

static func _parse_vector2i(val: Variant, context: ParserContext) -> Vector2i:
	var str_val = _parse_string(val)
	if str_val.is_empty():
		return Vector2i.ZERO
	var parts = str_val.split(";")
	if parts.size() < 2:
		context.log_error("Failed to parse Vector2i from '%s'" % str_val)
		return Vector2i.ZERO
	return Vector2i(int(parts[0]), int(parts[1]))

static func _parse_vector3(val: Variant, context: ParserContext) -> Vector3:
	var str_val = _parse_string(val)
	if str_val.is_empty():
		return Vector3.ZERO
	var parts = str_val.split(";")
	if parts.size() < 3:
		context.log_error("Failed to parse Vector3 from '%s'" % str_val)
		return Vector3.ZERO
	return Vector3(float(parts[0]), float(parts[1]), float(parts[2]))

static func _parse_vector3i(val: Variant, context: ParserContext) -> Vector3i:
	var str_val = _parse_string(val)
	if str_val.is_empty():
		return Vector3i.ZERO
	var parts = str_val.split(";")
	if parts.size() < 3:
		context.log_error("Failed to parse Vector3i from '%s'" % str_val)
		return Vector3i.ZERO
	return Vector3i(int(parts[0]), int(parts[1]), int(parts[2]))

static func _parse_vector4(val: Variant, context: ParserContext) -> Vector4:
	var str_val = _parse_string(val)
	if str_val.is_empty():
		return Vector4.ZERO
	var parts = str_val.split(";")
	if parts.size() < 4:
		context.log_error("Failed to parse Vector4 from '%s'" % str_val)
		return Vector4.ZERO
	return Vector4(float(parts[0]), float(parts[1]), float(parts[2]), float(parts[3]))

static func _parse_vector4i(val: Variant, context: ParserContext) -> Vector4i:
	var str_val = _parse_string(val)
	if str_val.is_empty():
		return Vector4i.ZERO
	var parts = str_val.split(";")
	if parts.size() < 4:
		context.log_error("Failed to parse Vector4i from '%s'" % str_val)
		return Vector4i.ZERO
	return Vector4i(int(parts[0]), int(parts[1]), int(parts[2]), int(parts[3]))

static func _parse_rect2(val: Variant, context: ParserContext) -> Rect2:
	var str_val = _parse_string(val)
	if str_val.is_empty():
		return Rect2()
	var parts = str_val.split(";")
	if parts.size() < 4:
		context.log_error("Failed to parse Rect2 from '%s'" % str_val)
		return Rect2()
	return Rect2(float(parts[0]), float(parts[1]), float(parts[2]), float(parts[3]))

static func _parse_rect2i(val: Variant, context: ParserContext) -> Rect2i:
	var str_val = _parse_string(val)
	if str_val.is_empty():
		return Rect2i()
	var parts = str_val.split(";")
	if parts.size() < 4:
		context.log_error("Failed to parse Rect2i from '%s'" % str_val)
		return Rect2i()
	return Rect2i(int(parts[0]), int(parts[1]), int(parts[2]), int(parts[3]))

static func _parse_list(val: Variant, parse_element: Callable, context: ParserContext) -> Array:
	if val == null or not (val is Array):
		return []
	var result: Array = []
	for item in val:
		result.append(parse_element.call(item))
	return result

static func _parse_list_inline(val: Variant, parse_inline: Callable) -> Array:
	if val == null or not (val is Array):
		return []
	var result: Array = []
	for item in val:
		if item is Dictionary:
			result.append(parse_inline.call(item))
	return result

static func _parse_dictionary(val: Variant, parse_key: Callable, parse_val: Callable, context: ParserContext) -> Dictionary:
	if val == null or not (val is Dictionary):
		return {}
	var result: Dictionary = {}
	for k in val.keys():
		result[parse_key.call(k)] = parse_val.call(val[k])
	return result
#endregion
''';
}

enum MetaEntityType {
  Class,
  Table,
}
