name: main

env:
  flutterVersion: "3.47.0"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, develop]
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Init flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{env.flutterVersion}}

      - name: Get dependencies
        run: flutter pub get

      - name: Build windows
        run: |
          flutter config --enable-windows-desktop
          flutter build windows --release

      - name: Upload windows build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/x64/runner/Release

  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Init flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{env.flutterVersion}}

      - name: Get dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --release

      - name: Upload web build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare linux
        run: |
          sudo apt-get update
          sudo apt install clang libgtk-3-dev ninja-build -y --fix-missing

      - name: Git checkout
        uses: actions/checkout@v4

      - name: Init flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{env.flutterVersion}}

      - name: Get dependencies
        run: flutter pub get

      - name: Build linux
        run: |
          flutter config --enable-linux-desktop
          flutter build linux --release

      - name: Upload linux build
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/linux/x64/release/bundle

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Init flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{env.flutterVersion}}

      - name: Get dependencies
        run: flutter pub get

      - name: Build macos
        run: |
          flutter config --enable-macos-desktop
          flutter build macos --release

      - name: Archive macos build
        run: |
          cd build/macos/Build/Products/Release
          zip -9 -y -r -q gceditor.zip gceditor.app

      - name: Upload macos build
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: build/macos/Build/Products/Release/gceditor.zip

  release:
    needs: [build-windows, build-web, build-linux, build-macos]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    permissions:
      contents: write
    steps:
      - name: Download windows build
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: windows-build

      - name: Download web build
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: web-build

      - name: Download linux build
        uses: actions/download-artifact@v4
        with:
          name: linux-build
          path: linux-build

      - name: Download macos build
        uses: actions/download-artifact@v4
        with:
          name: macos-build
          path: macos-build

      - name: Archive windows build
        uses: vimtor/action-zip@v1
        with:
          files: windows-build
          dest: gceditor_windows_${{ github.event.release.tag_name }}.zip

      - name: Archive web build
        uses: vimtor/action-zip@v1
        with:
          files: web-build
          dest: gceditor_web_${{ github.event.release.tag_name }}.zip

      - name: Archive linux build
        uses: vimtor/action-zip@v1
        with:
          files: linux-build
          dest: gceditor_linux_${{ github.event.release.tag_name }}.zip

      - name: Archive macos build
        uses: vimtor/action-zip@v1
        with:
          files: macos-build
          dest: gceditor_macos_${{ github.event.release.tag_name }}.zip

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            gceditor_windows_${{ github.event.release.tag_name }}.zip
            gceditor_web_${{ github.event.release.tag_name }}.zip
            gceditor_linux_${{ github.event.release.tag_name }}.zip
            gceditor_macos_${{ github.event.release.tag_name }}.zip

